### ISSUE TITLE
Batch operations

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#100]
We should think through the right UI/UX for doing batch operations like batch updates/deletes at either the Project/Folder/File levels

**Comment by erichhuang** [comment]
And batch operations for users too (being able to remove multiple people from a Project, change their privileges, add them). A good predicate is Github's team management.

**Comment by caseychoiniere** [comment]
For folder/file list batch operations I like the Google Inbox app style. If you don't use inbox, I added a quick example vid on ua_test and shared it.

**Comment by erichhuang** [comment]
I wish I could use Inbox, but I have to have Exchange too. That looks fine. I generally like the Material Design paradigms.

**Comment by caseychoiniere** [comment]
I split this into separate issues and I'm closing this one.
