### ISSUE TITLE
Apitoken not being cleared out causes redirect issue

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#101]
Seems that sometimes the api token cookie isn't cleared out. It's causing a redirect issue if this happens because there's an apiToken but it's also invalid. I think it happens if the user doesn't log out and then the apiToken expires while their computer is in a sleep state. I will set the token to expire identical to the token issued by the AS.

**Comment by erichhuang** [comment]
👍🏼

**Comment by caseychoiniere** [comment]
I pushed a fix for this but there seems be an issue with the DDS genportal script not running so I wasn't able to create a pull request on the DDS repo.
