### ISSUE TITLE
Footer flag is showing "UATest" in Dev

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#107]
![screenshot 2016-01-28 14 38 19](https://cloud.githubusercontent.com/assets/386675/12656560/f3306b6a-c5cc-11e5-8cd2-79f73bbac9e3.png)

**Comment by dmlond** [comment]
this is a duke-data-service issue, not a portal issue. we have to be able to run dds dev in development mode, without it flooding its memory.

**Comment by caseychoiniere** [comment]
I already opened an issue in DDS for this. I'm going to close this issue in portal if that's okay.
