### ISSUE TITLE
Project can't be edited

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#109]
Tried to change the name of a Project. Entered name change in dialog box and hit `Update`, and nothing happens

**Comment by caseychoiniere** [comment]
Erich, did you only try to edit the name? Right now the validation checks for edits in both name and description fields. Perhaps I should change this to validate as long as there is any value in the name and description text fields. That would make more sense I guess.

**Comment by erichhuang** [comment]
Any change should validate
