### ISSUE TITLE
Internet Explorer Blank Screen (problem with strict mode)

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#112]
IE shows blank white screen. Problem is `Multiple definitions of a property not allowed in strict mode` and is probably coming from one or more dev dependencies.

**Comment by jonturneratduke** [comment]
Cool. that's half the battle, just knowing what's giving us trouble. 
It'd be good to get this solved, as the Molecular Physiology Lab is pretty enthusiastic about using DS.

**Comment by caseychoiniere** [comment]
Well, if they like IE, at least they have low expectations ;)

**Comment by caseychoiniere** [comment]
Running the build with bug fix now. Will work on IE11 after integration tests run and deploy new portal.
