### ISSUE TITLE
firefox: focus change on adding new project member [Member Management]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#126]
When adding new member to project, focus changes to picklist as soon as candidate names are populated. if the user hits the backspace key (intending to change spelling of partial name), this navigates to previous browser page which will be the top-level Projects dashboard.

This appears to only be an issue in Firefox. Focus works correctly in Safari and Chrome (Mac).

**Comment by caseychoiniere** [comment]
This is a known bug with the autocomplete component from Material-UI. It's been logged in their repo. https://github.com/callemall/material-ui/issues/2968

**Comment by caseychoiniere** [comment]
Looks like they've actually fixed this bug and it should be available in their next update.
https://github.com/callemall/material-ui/pull/3356
