### ISSUE TITLE
With new determinate progress bar release, the Upload File modal becomes unresponsive [File Upload]

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#134]
I love the determinate progress bar, but I think we may have a side effect related to it:
I'm guessing there's some calculation going on, but the `Upload File` modal becomes unresponsive and I think, depending on the size of file, beachballs on a MacBook Pro.

**Comment by erichhuang** [comment]
The above was with Safari. With Chrome, the Modal becomes unresponsive after selecting the file to upload.

**Comment by erichhuang** [comment]
And to clarify with Safari, it's after the `Submit` button is hit.

**Comment by caseychoiniere** [comment]
Still unable to replicate this in any browser. Will leave open for now.

**Comment by caseychoiniere** [comment]
Unless this has shown up again I'm going to close this. I have still not run into this.
