### ISSUE TITLE
Batch Ops [Member management]

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#145]
Splitting issue #100 into specific issues

**Comment by caseychoiniere** [comment]
@mgardnerpsu @jonturneratduke @dmlond I think we need to have a way to add a whole group of people at once. The way the api for adding members currently works makes this really heavy on network traffic. Perhaps we should consider an endpoint that allows a user to create a team "template" (or something like that) that they can then make changes to if needed. 
It could be created once for a lab and then reused as needed. The project admin could then add or remove people from a project as needed but wouldn't need to add 10-20 people individually to get the project started. 
Perhaps a future feature?

**Comment by jonturneratduke** [comment]
With this current API, when you say "heavy on network traffic", can you give us a sense of the overhead? Are we talking about dozens/hundres/thousands of API calls, or ?? and what is the total execution time?  If each call only took a few ms, then would we be okay? Perhaps we defer until we have more profiling info. I think we'll want to make a pass over the current configuration/heroku/tools/code and find the bottlenecks. From there, wring out as much performance as possible from the endpoints we have, and then if it's still not meeting needs, talk through refactoring or addition of batch-type endpoints.  

I do like the idea of group management : selecting several people and giving that selection a name, then adding that group. It's a very common pattern we see in the use cases.

**Comment by erichhuang** [comment]
👍🏼

erich s. huang, md-phd
https://calendly.com/erich-huang

**Comment by caseychoiniere** [comment]
@jonturneratduke Basically each time you want to add a member you go through this process:

1.) Make call to search user name and populate autocomplete list based on user input into text area (could be one call could be 10 depending on the user and how well they know who they're searching for)
2.) Make a call to get the user id for the selected name
3.) Make a call to grant project permissions to that user
4.) Make a call to repopulate the user list with new data and update the UI.

So to add a team of 20 people it makes 80 calls minimum.

I think I can streamline this (and I should) by doing an optimistic update to the user list and adding the new user to the list without making the call in # 4

I could also possibly populate the autocomplete with an array of objects instead of an array of strings which could eliminate # 2 but I've found this has some pretty negative impacts on UI performance for the autocomplete and is probably not worth the slow user experience it creates.

Let's for a second consider the more important aspect of user experience though. Currently to add a member to a project a Project Admin has to do the following:

1.) Open menu and select "Add new member"
2.) Type member name
3.) Select proper name
4.) Select a role
5.) Click "Create member"

So for a project admin to add their team of 20 people they have to take 100 individual actions to make this happen. Pretty annoying.

While we could hack together something out of the current services that might work, it's not really a good solution because the user is still required to create it from scratch every single time. 

You could imagine the usefulness of a template for teams here. The admin could create it once and then use it over and over again with 1 or 2 clicks. They could also have different templates with different permissions defined and use which ever one makes sense for their project. 
If they needed to add or remove a few people it would still be quicker than building from scratch every time.

I think this is probably a "nice to have" feature but I definitely think it's worth putting on the road map at some point. 

Just my $.02

**Comment by mgardnerpsu** [comment]
I agree we need this functionality, and my guess is for a large research core this will get painful if they have to add members one at a time for each project they setup.  In the short term, at the time of project creation (or post creation) we could allow an option to copy membership setup from one project to another.  This is a bit of hack, but may be something we could do in the interim, and I think when a team "template" design is in place the source of the copy would be from a template vs. another project - so not all that different from an implementation standpoint.

**Comment by jonturneratduke** [comment]
Oh, I didn't realize it was so involved.  If we were able to knock down the round-trip times on those calls to milliseconds, then the chattiness might not be an issue, but if that's not possible then we need a way to deal with bulk lists or group sets.  As a stopgap, would it be too clunky to paste in a list of (comma/semicolon) delimited names, split into a list, then lookup each one and translate to a qualified name the way email apps work?

**Comment by jonturneratduke** [comment]
(Now that I think about it, would that same behavior be useful for tags? Imagine being able to enter "`beta, ready for review, confidential, funding code 123, no PHI`" and it assigns five tags?)

**Comment by caseychoiniere** [comment]
A comma separated list of names would work fine but only if everyone has the same permissions. 

And yes, should probably make it possible to add a comma separated list of tags.
