### ISSUE TITLE
UI refinements for batch delete [Styling]

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#148]
Love that we can now batch delete. Some suggestions for refinements of the UI:
- [ ] It may be just me, but Material Design's checkboxes are about the only element I'm not crazy about. Can we try radio buttons?
- [ ] I feel like the Trashcan is just floating out there, I wonder if we can just have flat "MOVE | DELETE" text buttons aligned right with "ADD FOLDER". The buttons would be grey until a radio button is selected and would become pink (matching the Upload button) when active. "MOVE" obviously would be a future feature.
  ![screen shot 2016-02-12 at 7 57 34 pm](https://cloud.githubusercontent.com/assets/386675/13024679/b3339e00-d1c6-11e5-8c09-eb78da21a921.png)

**Comment by erichhuang** [comment]
Also, I guess it'd be nice if the Snackbar had a "UNDO" option too.

**Comment by caseychoiniere** [comment]
I'm going to move Snackbar "UNDO" to a separate issue. It's more complex than it seems, especially for batch options.

**Comment by erichhuang** [comment]
I like the new `DELETE` button I now see on Dev much better. It doesn't work, but I wonder if that's due to Dev flakiness. I'd also make it the same pink as the `Upload` button.

**Comment by caseychoiniere** [comment]
I made changes to the delete button. I can make the change from checkboxes to radio buttons but I want to confirm first that you have a strong preference for this. Radio buttons are not really meant to be used in this way so it takes modification to the core functionality to make them work. 
https://www.google.com/design/spec/components/selection-controls.html#selection-controls-checkbox
![screen shot 2016-02-15 at 12 28 48 pm](https://cloud.githubusercontent.com/assets/10411174/13059635/7b899088-d3e0-11e5-937a-782a6adb276a.png)

Also, I'll fix delete button. Probably my error, not dev flakiness

**Comment by erichhuang** [comment]
I definitely aesthetically prefer the radio buttons (and concede I'm probably violating some design paradigm). It's up to you, especially if it takes extra work. I'd also make sure the `ADD FOLDER` button aligns with left border of the `Project Card`

**Comment by erichhuang** [comment]
Forgive me that my Mother was a designer and my sister is an architect: I notice that the shadows around the rectangular buttons is different than around the `Project Card`, i.e. the lower shadow of the `Project Card` is sharper and darker than with the `ADD FOLDER` button.

**Comment by caseychoiniere** [comment]
I think checkboxes are more appropriate here. Partially due to the use case and partially due to the fact that I would need to override the default behavior of the radio buttons provided by the framework we're using. 

As far as drop shadows not matching, you're absolutely right. I fixed that and the button alignment. Sometimes I make the mistake of aligning elements while I have my console open. That's a bad habit...
