### ISSUE TITLE
Batch Ops [Download Files]

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#150]
I guess if we're doing the other things, we need to be able to download as batches too. I guess the question in the future is whether a batch of files should be zipped. For now, I guess sequential downloads should be fine.

**Comment by caseychoiniere** [comment]
I'm thinking that if we're going to have this many options for 'batching', we need a different UI for this.Buttons look good on desktop but if we have 3 or 4 different options that show every time you check a box, this get's clunky looking on a small device. This might be an icon menu with a dropdown or it might be smaller icon buttons like I had previously. Any thoughts?

**Comment by erichhuang** [comment]
If I recall correctly, Microsoft office 365 invokes the modal for best operations. When I get back to my work station tomorrow morning I'll try to remember to give you a screenshot.

**Comment by erichhuang** [comment]
So when one selects > 1 email on Office365's web app for Outlook, one get's this modal on the right.
<img width="1278" alt="screen shot 2016-02-17 at 9 04 30 am" src="https://cloud.githubusercontent.com/assets/386675/13111743/7f78a848-d555-11e5-898b-c7501ef8435b.png">

**Comment by caseychoiniere** [comment]
Only problem with this approach is that it doesn't solve the issue of mobile. I'm thinking something along the lines of an app bar/toolbar that shows/hides when items are selected. This tool bar could have smaller icons and show a count of items selected. It would be a good space that would allow for adding additional options down the road without having to make big layout changes. Another option would be a dropdown list of actions the user could take on selected items. Again, Google Inbox does a nice job of this. 
![screen shot 2016-02-24 at 2 29 56 pm](https://cloud.githubusercontent.com/assets/10411174/13303278/3444ee96-db03-11e5-8ff5-fe6f0696feb6.png)
![screen shot 2016-02-24 at 2 30 14 pm](https://cloud.githubusercontent.com/assets/10411174/13303285/3b90ab9a-db03-11e5-84c2-ed9ddb543752.png)

**Comment by caseychoiniere** [comment]
Something like this is what I propose. Feedback? And of course this only shows when items are selected. @erichhuang 
![screen shot 2016-02-24 at 3 30 21 pm](https://cloud.githubusercontent.com/assets/10411174/13304758/9a206396-db0b-11e5-94ba-9a5aed9e7039.png)

**Comment by caseychoiniere** [comment]
@erichhuang is this design okay with you? I think it fits the use case better than buttons and allows more flexibility for adding future features. I've already coded it up, if it's okay, I'll go ahead and push it to dev today.

**Comment by erichhuang** [comment]
Let's try it on Dev

**Comment by caseychoiniere** [comment]
@erichhuang When you get a chance, let me know your thoughts? I can change the background color back to white or a different shade of grey, I just wanted the toolbar to stand out among the other cards on the page.

**Comment by erichhuang** [comment]
Try the pink and perhaps separate the download and delete buttons with the "X Selected" text so reduce the chance of fat fingering or erroneously clicking the other action?

**Comment by caseychoiniere** [comment]
I can do that. Separating the buttons with the "X selected" sort of negates the flexibility of adding more options down the road though. Instead, perhaps I should just make the targets a bit bigger or increase the padding for each target. I do have a confirmation modal which would keep people from accidentally deleting when they are trying to download or vise versa.

**Comment by erichhuang** [comment]
Modal should be enough. Let's not get too big.
