### ISSUE TITLE
Race condition won't go away

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#165]
![racingds](https://cloud.githubusercontent.com/assets/386675/13164466/7dde5e54-d683-11e5-8b9e-19411008bb39.gif)

**Comment by caseychoiniere** [comment]
I'm assuming this is the redirect loop we've been having some issues with? Hard to tell from the gif. Did you happen to inspect your resources and see if there were any strange cookies lingering? There shouldn't be. I'll work on figuring out what else might be causing this.

**Comment by caseychoiniere** [comment]
Actually, if this is on production, I hadn't merged the fix for it yet. I was waiting to get the mobile click event bug fixed first. The fix will be deployed in a minute.
