### ISSUE TITLE
Unable to upload empty file.

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service-portal#176]
Found this testing against https://uatest.dataservice.duke.edu

Steps:
Lock onto a project.
Click upload fab button.
Choose an empty file.
Click Upload

At this point there was no UI indication of what was happening.

Looking at the console there is an error:

```
Uncaught TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.f.startUpload.preEmit @ main.js:9
e.exports.trigger @ main.js:8
(anonymous function) @ main.js:8
(anonymous function) @ main.js:8
r.run @ main.js:1
o @ main.js:1
```

I think the issue is we are passing null to readAsArrayBuffer.

Thanks.

**Comment by caseychoiniere** [comment]
@johnbradley  thanks, nice catch. I was slicing the file using a while loop and had it set to check if the start was less than the size so if the file was empty it was failing. Rather than 

``` javascript
while (start < SIZE)
```

In order to account for an empty file it should have been

``` javascript
 // describe chunk details
    while (start <= SIZE) {
        slicedFile = blob.slice(start, end);
        details.chunks.push({
            number: chunkNum,
            start: start,
            end: end,
            chunkUpdates: {
                status: null,
                progress: 0
            },
            retry: 0
        });
        // increment to next chunk
        start = end;
        end = start + BYTES_PER_CHUNK;
        chunkNum++;
    }
```
