### ISSUE TITLE
Header Alignment [Styling]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#185]
**Sender**: erich.huang@duke.edu
**Comment**: Somehow the alignment of these two headers always catches my attention. I guess at some point consider whether "Account Overview" should sit above the box or not. Also consider whether to All Caps and/or Bold these.
[Open #21 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/21)

![Usersnap Feedback - Somehow the alignment of these two headers always catches my attention. I (...)](https://usersnappublic.s3.amazonaws.com/2016-02-24/22-38/3e04ed2b-9400-4dd8-8b49-0a76a8dc3edf.png)

**Browser**: Safari 9 (Macintosh)
**Referer**: [https://dataservice.duke.edu/portal/#/home](https://dataservice.duke.edu/portal/#/home)
**Screen size**: 2560 x 1440 **Browser size**: 1849 x 1098

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Maybe it doesn't even need the "Account Overview" title???

**Comment by erichhuang** [comment]
Yeah, perhaps there's no need for that title.
