### ISSUE TITLE
Add Project Affiliates count to overview 

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#186]
Use affiliates endpoint to add "Collaborators" count to account overview

**Comment by mgardnerpsu** [comment]
The intent of `project/{id}/affiliates` was to associate individuals and their organizational role in the context of a project (such as PI) independent of access control granted via `/projects/{id}/permissions`.  We are not using affiliates at this point in Portal, but I can foresee us allowing PI to be captured for a project at some point, and perhaps Co-PI(s), etc.  @erichhuang your thoughts?
I think for now to implement this enhancement, just count number of users with project level permissions.  Do you want this at the API level? We could create endpoint for `/project/{id}/metrics` - or something liken to that?  I can see needing this as stub for other project level metrics down the road as well - total storage, total files, etc...
