### ISSUE TITLE
Usersnap Feedback - Convert these time stamps to a more human readable format

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#189]
**Sender**: casey.choiniere@gmail.com
**Comment**: Convert these time stamps to a more human readable format
[Open #24 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/24)
**Notes**:
- (1) Convert these time stamps to a more human readable format

![Usersnap Feedback - Convert these time stamps to a more human readable format](https://usersnappublic.s3.amazonaws.com/2016-02-25/19-20/f668e172-349a-465b-b6da-b85f78491e29.png)

**Browser**: Chrome 48 (Macintosh)
**Referer**: [http://localhost:1337/#/project/afca72d2-7bb4-47f8-b32e-b52bfc7e67a6](http://localhost:1337/#/project/afca72d2-7bb4-47f8-b32e-b52bfc7e67a6)
**Screen size**: 1920 x 1080 **Browser size**: 1598 x 956

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by erichhuang** [comment]
Yeah, something like "9 November, 2016 at 3:35 PM"
