### ISSUE TITLE
Usersnap Feedback - Don't stretch button all the way to left margin, extra padding between dow[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#199]
**Sender**: erich.huang@duke.edu
[Open #29 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/29)
**Notes**:
- (1) Don't stretch button all the way to left margin, extra padding between download and delete icons, Use same pink shade.

![Usersnap Feedback - Don't stretch button all the way to left margin, extra padding between dow(...)](https://usersnappublic.s3.amazonaws.com/2016-03-02/21-08/36551999-283f-4067-a23f-e72bf1c5e5ca.png)

**Browser**: Safari 9 (Macintosh)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/folder/c9a7314d-151c-4e57-90f1-a9983cc6c81c](https://dev.dataservice.duke.edu/portal/#/folder/c9a7314d-151c-4e57-90f1-a9983cc6c81c)
**Screen size**: 2560 x 1440 **Browser size**: 1700 x 1329

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@erichhuang By saying "Don't stretch button all the way to left margin" are you referring to the 'toolbar' that the buttons sit on?
