### ISSUE TITLE
Usersnap Feedback - Need a way to download more than one file at a time. Can we add a new butt[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#202]
**Sender**: jonathan.turner@duke.edu
**Comment**: Need a way to download more than one file at a time. Can we add a new button (Like delete, above) that says "Download" with a count??

[Open #31 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/31)

![Usersnap Feedback - Need a way to download more than one file at a time. Can we add a new butt(...)](https://usersnappublic.s3.amazonaws.com/2016-03-07/21-53/81acdafe-a824-497a-b796-54d2917c8cda.png)

**Browser**: Firefox 44 (Mac OS X Mavericks)
**Referer**: [https://dataservice.duke.edu/portal/#/folder/56e83943-2a23-4903-af4d-2dc823154b66](https://dataservice.duke.edu/portal/#/folder/56e83943-2a23-4903-af4d-2dc823154b66)
**Screen size**: 1680 x 1050 **Browser size**: 3048 x 1616

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
This is already implemented on Dev. It's a different design but the same idea.@jonturneratduke Would you like me to promote to Production?

**Comment by caseychoiniere** [comment]
Closing. Implemented on dev.

**Comment by caseychoiniere** [comment]
@erichhuang @jonturneratduke Just let me know if/when you want me to promote this to production

**Comment by erichhuang** [comment]
Pull the trigger 👍🏼

**Comment by jonturneratduke** [comment]
Awesome! Yeah, push that to prod. 

I was demoing today to some folks and they said "Wish I could download more than one file" which segued into "well, let me show you the feedback button..."
