### ISSUE TITLE
Usersnap Feedback - I believe this File UUID is truncated? I think it should be "se7673fbb-6aa[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#217]
**Sender**: erich.huang@duke.edu
[Open #32 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/32)
**Notes**:
- (1) I believe this File UUID is truncated? I think it should be "se7673fbb-6aa0-4ba8-bb41-1e69fd148336"

If you go to the File page, it shows "se7673fbb-6aa0-4ba8-bb41-1e69fd148336"

![Usersnap Feedback - I believe this File UUID is truncated? I think it should be "se7673fbb-6aa(...)](https://usersnappublic.s3.amazonaws.com/2016-03-09/18-27/af3141d8-e9ca-4ba8-9fa3-f0d53c85aa49.png)

**Browser**: Safari 9 (Macintosh)
**Referer**: [https://dataservice.duke.edu/portal/#/folder/6a647ff4-30a0-4617-bd1c-45597914efc1](https://dataservice.duke.edu/portal/#/folder/6a647ff4-30a0-4617-bd1c-45597914efc1)
**Screen size**: 2560 x 1440 **Browser size**: 1700 x 1333

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Ah, this was a "fat finger" from hitting CMD+S in my IDE. Left a rogue "s" in the div containing the UUID. Fixed it.
