### ISSUE TITLE
Usersnap Feedback - Not able to download a file. I tried within a folder and clicking the down[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#222]
**Sender**: James.fayson@duke.edu
**Comment**: Not able to download a file. I tried within a folder and clicking the download icon. I also tried selecting the the file and clicking the small download icon... still no luck.  
[Open #35 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/35)

![Usersnap Feedback - Not able to download a file. I tried within a folder and clicking the down(...)](https://usersnappublic.s3.amazonaws.com/2016-03-16/18-57/3ab00dc1-882a-43a7-8677-a19374620cae.png)

**Browser**: Chrome 49 (Windows 7)
**Referer**: [https://dataservice.duke.edu/portal/#/file/d0aaa5d9-9479-4154-ac8f-faf18221fe1a](https://dataservice.duke.edu/portal/#/file/d0aaa5d9-9479-4154-ac8f-faf18221fe1a)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 769

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke Can you see if you can get more info on this? I can see that it's a .mpp extension and that's all. I'd like to know if this continues to persist with this file or if it was a momentary glitch. Downloads seem to be working fine so I'm wondering what's going on here. Additionally, the client logic behind downloads is very basic, we simply open the supplied URL from swift and the file downloads into the browser. This makes me think this might be a swift issue? Perhaps a corrupted upload or a bad url??? Worth investigating more.

**Comment by caseychoiniere** [comment]
@jonturneratduke Never mind. He realized it was because pop up blocker was on.
