### ISSUE TITLE
Usersnap Feedback - I see the problem... Pop-up blockers was on... however, I did not received [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#223]
**Sender**: James.fayson@duke.edu
**Comment**: I see the problem... Pop-up blockers was on... however, I did not received a warning until after I logged out then back in....
[Open #36 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/36)

![Usersnap Feedback - I see the problem... Pop-up blockers was on... however, I did not received (...)](https://usersnappublic.s3.amazonaws.com/2016-03-16/19-17/03f2e6aa-6bd8-476e-b27a-88195538f290.png)

**Browser**: Chrome 49 (Windows 7)
**Referer**: [https://dataservice.duke.edu/portal/#/project/b300bb5e-2730-4e3f-ab2d-4d48f5557425](https://dataservice.duke.edu/portal/#/project/b300bb5e-2730-4e3f-ab2d-4d48f5557425)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 717

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Hmmm, that's weird. That would be browser specific though.
