### ISSUE TITLE
Usersnap Feedback - Is it worth considering whether this screen will show the API Token too?

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#233]
**Sender**: erich.huang@duke.edu
**Comment**: Is it worth considering whether this screen will show the API Token too?
[Open #39 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/39)

![Usersnap Feedback - Is it worth considering whether this screen will show the API Token too?](https://usersnappublic.s3.amazonaws.com/2016-03-22/22-52/5a328ce0-1656-48b2-8015-0eed3ff6e972.png)

**Browser**: Safari 9 (iOS)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/agent/2770e809-d0e8-4f7d-9fcf-fa6a6491ccbb](https://dev.dataservice.duke.edu/portal/#/agent/2770e809-d0e8-4f7d-9fcf-fa6a6491ccbb)
**Screen size**: 375 x 667 **Browser size**: 375 x 559

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@erichhuang Yes, I think it should. In fact I think it should be in place of ID

**Comment by caseychoiniere** [comment]
It's an extra server call on every list item though. Making it a little more of a PITA

**Comment by caseychoiniere** [comment]
Might be very slow rendering because the API_Token isn't returned in the list of agents. The agent list returns 

``` javascript
{
  "results": [
    {
      "id": "9a4c28a2-ec18-40ed-b75c-3bf5b309715f",
      "name": "Hash computation agent",
      "description": null,
      "repo_url": null,
      "is_deleted": false,
      "audit": {}
    }
  ]
}
```

and then you have to make separate call to get the key

``` javascript
{
  "key": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ...",
  "created_on": "2015-01-01T12:00:00Z"
}
```

Which if I'm trying to make those calls as the list is rendering, can be an issue if list item renders before server call finishes and `key` isn't in React state yet. Wonder if it's worth the overhead? I was originally thinking that the key was returned in the agent object in the list of agents.

**Comment by dmlond** [comment]
Based on usage patterns of amazon, google, even redcap, software_agent api_keys were meant to be a controlled piece of information viewable only on demand by the owner of the software_agent. At some point, we will want to allow users to search for other users software_agents, and request the api_key for an agent from its owner, at which point we might make it available to those users on demand as well, but we dont want it to be available by default in the list or show output for users that do not own the software_agent when we get to that point.

**Comment by caseychoiniere** [comment]
Than I'd say we don't bother putting it in the list now. If the API isn't designed that way, there's a reason for it and I'd say we just keep it as is for now. Maybe even just list the name, no id. Thanks Darin for the feedback.

**Comment by dmlond** [comment]
ok. dont forget about the description. At some point, those could go into elasticsearch to facilitate searches. Its ok if the ID is not visible.

**Comment by caseychoiniere** [comment]
Sure, could display name, description, repo URL (if there's a description or repo url). I just think ID is kind of useless to the user and might be confused as the api_key.

**Comment by dmlond** [comment]
I agree
