### ISSUE TITLE
Usersnap Feedback - Still would prefer having the API *Token*

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#239]
**Sender**: erich.huang@duke.edu
**Comment**: Still would prefer having the API _Token_
[Open #40 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/40)

![Usersnap Feedback - Still would prefer having the API *Token*](https://usersnappublic.s3.amazonaws.com/2016-03-24/02-13/7de316da-c615-4492-bdaa-9f86105ec24a.png)

**Browser**: Safari 9 (Macintosh)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/agents](https://dev.dataservice.duke.edu/portal/#/agents)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Will be on next build
