### ISSUE TITLE
Usersnap Feedback - Cool. Only thing I'd say is that it says "Key" as opposed to "Token"

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#242]
**Sender**: erich.huang@duke.edu
**Comment**: Cool. Only thing I'd say is that it says "Key" as opposed to "Token"
[Open #42 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/42)

![Usersnap Feedback - Cool. Only thing I'd say is that it says "Key" as opposed to "Token"](https://usersnappublic.s3.amazonaws.com/2016-03-25/17-52/3f64d792-339d-434b-8243-70a24cdfa2cd.png)

**Browser**: Safari 9 (iOS)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/agents](https://dev.dataservice.duke.edu/portal/#/agents)
**Screen size**: 375 x 667 **Browser size**: 375 x 559

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Yep, I think I already fixed that along with a few other minor details and it'll show on the next build. Thanks.
