### ISSUE TITLE
Usersnap Feedback - I think it'd be cool if the Token string were in a fixed-width font and red

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#243]
**Sender**: erich.huang@duke.edu
**Comment**: I think it'd be cool if the Token string were in a fixed-width font and red
[Open #43 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/43)

![Usersnap Feedback - I think it'd be cool if the Token string were in a fixed-width font and red](https://usersnappublic.s3.amazonaws.com/2016-03-25/19-19/5c67caff-86f7-4f81-a926-4944147be402.png)

**Browser**: Safari 9 (Macintosh)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/agents](https://dev.dataservice.duke.edu/portal/#/agents)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 712

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I'll make it monospace font but there's a bug in the `multi-line text field` in Material-UI that currently makes it not possible to change the text field text color. There will be a fix for this soon and then I can change it. https://github.com/callemall/material-ui/pull/3099
