### ISSUE TITLE
Usersnap Feedback - I actually like these more whitespace padded cards in Prod than the new, s[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#244]
**Sender**: erich.huang@duke.edu
**Comment**: I actually like these more whitespace padded cards in Prod than the new, smaller ones in Dev
[Open #44 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/44)

![Usersnap Feedback - I actually like these more whitespace padded cards in Prod than the new, s(...)](https://usersnappublic.s3.amazonaws.com/2016-03-25/19-21/643bea67-0d6c-4b65-9dd6-6ec22490ab4f.png)

**Browser**: Safari 9 (Macintosh)
**Referer**: [https://dataservice.duke.edu/portal/#/home](https://dataservice.duke.edu/portal/#/home)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 712

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@erichhuang Okay, the problem with them is they don't play nice in internet explorer. The core styles of the component (that I can't override from the framework) have issues with text wrapping. Also, they don't resize and show all text on mobile or tablets, instead it has to be truncated or worse, if there's a long title, they just cut off the description. The current cards resize and all cards take on the size of the largest card in the list, although I truncate the description to keep them from looking too weird if someone has a really long description. So, I'd prefer to keep the ones in dev but if you're totally opposed I can switch them back and people using IE can just deal with a funky layout.

**Comment by caseychoiniere** [comment]
The markup is cleaner too. I can set a min height and increase padding. That will get them closer to the original cards while maintaining the better functionality.
