### ISSUE TITLE
Usersnap Feedback - back button refers to invalid address: https://dev.dataservice.duke.edufil[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#251]
**Sender**: jonathan.turner@duke.edu
**Comment**: back button refers to invalid address: https://dev.dataservice.duke.edufile/48a59c88-5428-4008-83a7-c3e50e4dd3d1
[Open #45 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/45)

![Usersnap Feedback - back button refers to invalid address: https://dev.dataservice.duke.edufil(...)](https://usersnappublic.s3.amazonaws.com/2016-04-01/16-39/95e52bfe-0599-4ab3-8a21-b7f8eb843706.png)

**Browser**: Firefox 45 (Mac OS X Mavericks)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/version/4e4d86db-27a8-42bb-8938-38efb9bbd896](https://dev.dataservice.duke.edu/portal/#/version/4e4d86db-27a8-42bb-8938-38efb9bbd896)
**Screen size**: 1680 x 1050 **Browser size**: 2858 x 996

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Thanks! Fixed on next build.
