### ISSUE TITLE
Usersnap Feedback - I have uploaded one more version than the one that is shown.  Version 2 on[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#252]
**Sender**: jonathan.turner@duke.edu
**Comment**: I have uploaded one more version than the one that is shown.  Version 2 only showed up when I uploaded version 3. (which is not shown). the most recent version did not have a version comment.
[Open #46 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/46)

![Usersnap Feedback - I have uploaded one more version than the one that is shown.  Version 2 on(...)](https://usersnappublic.s3.amazonaws.com/2016-04-01/16-44/0b112ff5-c001-4480-bb06-d90a7d2eb379.png)

**Browser**: Firefox 45 (Mac OS X Mavericks)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/file/48a59c88-5428-4008-83a7-c3e50e4dd3d1](https://dev.dataservice.duke.edu/portal/#/file/48a59c88-5428-4008-83a7-c3e50e4dd3d1)
**Screen size**: 1680 x 1050 **Browser size**: 3150 x 996

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke  This is how the API works. The most recently uploaded version slides into place as the "current file" and the previous file is versioned. So you will only ever see the versions other than the current file. In fact the API doesn't even give a version number to the most recent version. It only gets a version number once it is replaced. It felt a little weird to me at first too. I figured if you upload a new version, it should get a version number and then I could display it in the list item. Erich had said he wanted this in this issue #99 in the comments near the bottom. If this isn't the intended API behavior we should raise a flag ASAP.

**Comment by caseychoiniere** [comment]
@dmlond or @dmann any feedback on this?

**Comment by dmann** [comment]
I believe the API is working according to what is outlined in the apiary documentation. @mgardnerpsu, does this sound right to you?

**Comment by caseychoiniere** [comment]
I agree @dmann seems like it works as outlined. It would be nice if the file version number would show on the current version though. Logically as users we know that if there are previous versions, the most current file is also a version, the newest version.  

> Updates one or more file resource properties; if this action includes and upload property in the request, the previous file resource is transitioned to version history (see File Versions).Note: Only the upload and label properties for the file are versioned; all other file properties and relationships, such as name, tags, etc. are not versioned, and they will not vary from version to version.

**Comment by mgardnerpsu** [comment]
To make this more logical to end users I see a couple approaches we could take:
1. In the "Version History" listing show "Version: Current" (this would be the current file resource - i.e. "dds-file") at the top of the list followed by the "version" history in descending order (i.e. "Version: 2", "Version: 1")
2. Include the "version" property in the current file resource; this would default to 1 when file resource is created and we would increment when it is replaced with new version. (i.e. assigned new upload object).

In addition, I think we should set the version "label" to "Initial version" when the file is created/versioned for the first time (i.e. this would be the default "label" for "version: 1" if the user/client app did not provide one) 

Feedback welcome...

**Comment by caseychoiniere** [comment]
I like these ideas. 1.) is easy to implement and makes sense. 2.) would make sure that all file resources have a version, and it is logical that the initial file resource is version 1.

And I think that setting the label on the initial file upload to "Initial version" or something similar also makes sense and solves the issue that @mgardnerpsu and I were discussing yesterday about the issue with adding labels to files when doing a multiple file upload.

**Comment by jonturneratduke** [comment]
@mgardnerpsu - great ideas!!

**Comment by caseychoiniere** [comment]
I've implemented all of these ideas now with the exception of (2) Include the "version" property in the current file resource; this would default to 1 when file resource is created and we would increment when it is replaced with new version. (i.e. assigned new upload object). 
I think it would be great if we could do this but that's probably an issue to open in DDS.
