### ISSUE TITLE
Usersnap Feedback - Perhaps show the version name/label here? I'd say hash too, but that's pro[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#256]
**Sender**: erich.huang@duke.edu
**Comment**: Perhaps show the version name/label here? I'd say hash too, but that's probably a sore point now for us :)
[Open #48 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/48)

![Usersnap Feedback - Perhaps show the version name/label here? I'd say hash too, but that's pro(...)](https://usersnappublic.s3.amazonaws.com/2016-04-02/00-31/6f792c37-9118-4490-9a20-e99bf7598a22.png)

**Browser**: Safari 9 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/file/286ad7da-027a-4f1b-a903-e403a73cbe18](https://dev.dataservice.duke.edu/portal/#/file/286ad7da-027a-4f1b-a903-e403a73cbe18)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I have it built to show the version label, assuming they add one when they create a new version. I wonder why it's not showing for you? Did you add labels to these versions when you created them? I also added the current file object to show at the top of the list as the `current version`. That will show in a few minutes with the new build.

**Comment by caseychoiniere** [comment]
This should be fixed now with the latest build. Working fine for me.
