### ISSUE TITLE
Usersnap Feedback - Probably show: Version 2, ID:abcdefgh-12345-xyz

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#257]
**Sender**: erich.huang@duke.edu
[Open #49 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/49)
**Notes**:
- (1) Probably show:
  Version 2, ID:abcdefgh-12345-xyz

![Usersnap Feedback - Probably show: Version 2, ID:abcdefgh-12345-xyz](https://usersnappublic.s3.amazonaws.com/2016-04-02/00-52/fea8ea2f-3a7d-4c80-b203-96cdb0ca2f72.png)

**Browser**: Safari 9 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/project/e1336b96-451a-42b2-91e4-e949088e8230](https://dev.dataservice.duke.edu/portal/#/project/e1336b96-451a-42b2-91e4-e949088e8230)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
They need to add this to the API in order to show the version here. Right now the version number isn't returned in the current file object.
