### ISSUE TITLE
Usersnap Feedback - Should these buttons be the same shade of blue as the header?

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#259]
**Sender**: erich.huang@duke.edu
[Open #50 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/50)
**Notes**:
- (1) Should these buttons be the same shade of blue as the header?

![Usersnap Feedback - Should these buttons be the same shade of blue as the header?](https://usersnappublic.s3.amazonaws.com/2016-04-02/02-08/1b28f07d-7872-4605-987b-f126f5889ea7.png)

**Browser**: Safari 9 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/file/286ad7da-027a-4f1b-a903-e403a73cbe18](https://dev.dataservice.duke.edu/portal/#/file/286ad7da-027a-4f1b-a903-e403a73cbe18)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
If you want

**Comment by caseychoiniere** [comment]
They'll be changed on next build
