### ISSUE TITLE
Usersnap Feedback - Seems like the grey darker line on the upper border of these, doesn't exte[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#263]
**Sender**: erich.huang@duke.edu
**Comment**: Seems like the grey darker line on the upper border of these, doesn't extend all the way on all the lines below the top one.
[Open #51 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/51)

![Usersnap Feedback - Seems like the grey darker line on the upper border of these, doesn't exte(...)](https://usersnappublic.s3.amazonaws.com/2016-04-05/22-36/32037a35-1d83-479d-878a-b64a0bb89372.png)

**Browser**: Safari 9 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/file/286ad7da-027a-4f1b-a903-e403a73cbe18](https://dev.dataservice.duke.edu/portal/#/file/286ad7da-027a-4f1b-a903-e403a73cbe18)
**Screen size**: 2560 x 1440 **Browser size**: 1600 x 1333

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Seems to be the way this list component is built by frameWork7. I can't override this style but I can try using another component possibly.
