### ISSUE TITLE
Usersnap Feedback - The disclaimer says "accept" but the button says "agree"

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#289]
**Comment**: The disclaimer says "accept" but the button says "agree"
[Open #56 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/56)

![Usersnap Feedback - The disclaimer says "accept" but the button says "agree"](https://usersnappublic.s3.amazonaws.com/2016-04-13/14-54/80c1b491-c8ef-4418-bf2c-a60a9bc7b049.png)

**Browser**: Microsoft Internet Explorer 11 (Windows 7)
**Referer**: [https://dataservice.duke.edu/portal#/home](https://dataservice.duke.edu/portal#/home)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 911

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Will be fixed on next build. Nice catch, thanks.
