### ISSUE TITLE
Usersnap Feedback - When trying to open a file within a folder, you receive a 404 error.

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#290]
**Sender**: James.fayson@duke.edu
**Comment**: When trying to open a file within a folder, you receive a 404 error.
[Open #57 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/57)

![Usersnap Feedback - When trying to open a file within a folder, you receive a 404 error.](https://usersnappublic.s3.amazonaws.com/2016-04-13/17-11/6d00deab-b60c-4c40-a469-1bea7c53dcbe.png)

**Browser**: Chrome 49 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/notFound](https://dataservice.duke.edu/#/notFound)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 769

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@dmlond  This is happening because `GET/versions`  is returning a 404. It should just return `[ ]` if there are no versions yet. Is the file versioning API set up on prod yet?

**Comment by dmlond** [comment]
yes. we are fixing that.
