### ISSUE TITLE
Usersnap Feedback - Images broken in prod

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#291]
**Comment**: Images broken in prod
[Open #58 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/58)
**Notes**:
- (1) Images are broken in Prod

![Usersnap Feedback - Images broken in prod](https://usersnappublic.s3.amazonaws.com/2016-04-13/17-36/4642e020-cc99-4d72-85b6-30b24e863fef.png)

**Browser**: Chrome 49 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/portal/#/login](https://dataservice.duke.edu/portal/#/login)
**Screen size**: 1440 x 900 **Browser size**: 2880 x 1514

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Seem to be working fine now
