### ISSUE TITLE
Usersnap Feedback - javascript console reported a RangeError: maximum call stack size exceeded

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#292]
**Sender**: None
**Comment**: javascript console reported a RangeError: maximum call stack size exceeded
[Open #59 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/59)

![Usersnap Feedback - javascript console reported a RangeError: maximum call stack size exceeded](https://usersnappublic.s3.amazonaws.com/2016-04-13/18-56/27a04ede-df63-4caa-bd58-b36243424f7c.png)

**Browser**: Chrome 49 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/file/f95696b7-706f-4e8b-9c85-c81ea8293026](https://dataservice.duke.edu/#/file/f95696b7-706f-4e8b-9c85-c81ea8293026)
**Screen size**: 1920 x 1080 **Browser size**: 1440 x 379

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dmlond** [comment]
I was hoping usersnap would take a picture of both the portal and the javascript console that I had open, but it didnt. It hit the maximum call stack exceeded issue in the crypto md5 module.

**Comment by caseychoiniere** [comment]
@dmlond was this while uploading a file? If so, how big was the file?

**Comment by dmlond** [comment]
yes. The upload completed. I went to logout, and I got a popup warning me that if I leave the page, the upload will not complete, so I chose 'stay on page' but I noticed that in the console log. I wonder if it is something to do with the web workers?

**Comment by jonturneratduke** [comment]
(I'm wondering if this might be related to Chris S's 900MB file upload failure the other day.)

**Comment by caseychoiniere** [comment]
It's possibly related but I can't reproduce this at all. The web workers shouldn't be causing this either. They just process their work and then clean themselves up afterwards.
