### ISSUE TITLE
Usersnap Feedback - It looks like code was injected into the project descriptions. Is this int[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#293]
**Sender**: jonathan.turner@duke.edu
**Comment**: It looks like code was injected into the project descriptions. Is this intentional??
[Open #60 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/60)

![Usersnap Feedback - It looks like code was injected into the project descriptions. Is this int(...)](https://usersnappublic.s3.amazonaws.com/2016-04-13/20-38/d62abd77-1819-4644-bdc3-96e921b5fab6.png)

**Browser**: Firefox 45 (Mac OS X Mavericks)
**Referer**: [https://dev.dataservice.duke.edu/#/home](https://dev.dataservice.duke.edu/#/home)
**Screen size**: 1680 x 1050 **Browser size**: 3352 x 1852

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Nope. Shoot.

**Comment by caseychoiniere** [comment]
Yes, actually I had just copied and pasted this in the description when I was testing the description truncation.
