### ISSUE TITLE
Usersnap Feedback - Is there a way to shrink the large blue box at the bottom of the page?  It [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#306]
**Comment**: Is there a way to shrink the large blue box at the bottom of the page?  It takes up half the screen and makes you have to scroll more than you should.  
[Open #62 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/62)

![Usersnap Feedback - Is there a way to shrink the large blue box at the bottom of the page?  It (...)](https://usersnappublic.s3.amazonaws.com/2016-04-18/16-15/155c2472-c58b-4478-8f8d-9772f8609539.png)

**Browser**: Chrome 49 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/folder/b56bec78-b76e-48f4-9b2b-f513b9928d77](https://dataservice.duke.edu/#/folder/b56bec78-b76e-48f4-9b2b-f513b9928d77)
**Screen size**: 1024 x 768 **Browser size**: 1006 x 615

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke The answer to this is yes. With the caveat that if you guys want this PHI statement in the footer, it's going to need to be pretty large still to account for that. I would love if the footer was very small and the PHI statement could find it's way somewhere else...

**Comment by caseychoiniere** [comment]
I can make this a bit smaller.
