### ISSUE TITLE
Long Project titles wrap funny

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#31]
![alt tag](https://dl.dropboxusercontent.com/s/md03a0howipmcjw/Screen%20Shot%202016-01-04%20at%209.38.22%20AM.png)

**Comment by caseychoiniere** [comment]
Erich, are you on uatest or dev? I can't seem to replicate this.  Even if that's the case I think the wrapping is an issue with the description and ID when the title is long.
<img width="1419" alt="screen shot 2016-01-04 at 9 15 49 am" src="https://cloud.githubusercontent.com/assets/10411174/12095504/e9446514-b2c3-11e5-8f9f-4480105d1390.png">

**Comment by caseychoiniere** [comment]
<img width="1216" alt="screen shot 2016-01-04 at 9 26 55 am" src="https://cloud.githubusercontent.com/assets/10411174/12095684/58212f0c-b2c5-11e5-9059-23bc7960d11e.png">

**Comment by erichhuang** [comment]
I'm on Dev. How possible would it be to just add an ellipsis "..." after a cut off of X characters?

**Comment by caseychoiniere** [comment]
There are solutions to this. CSS text-overflow is one solution with the caveat that it adds the ellipsis only on a single line which is pretty limiting. Could implement a JS solution but it can be a bit hacky looking when it comes to RWD as you're basically guessing at what length the text should be cut off. I'll look for a better solution.

**Comment by caseychoiniere** [comment]
Implemented a basic JS solution for truncating long titles/descriptions and adding an ellipsis. Will look into more elegant, responsive solution in the future.

**Comment by caseychoiniere** [comment]
<img width="1216" alt="screen shot 2016-01-04 at 9 26 55 am" src="https://cloud.githubusercontent.com/assets/10411174/12104923/d1fe2a70-b304-11e5-8556-b1e70b4f9761.png">

**Comment by caseychoiniere** [comment]
![screen shot 2016-01-04 at 5 01 26 pm](https://cloud.githubusercontent.com/assets/10411174/12104928/de3b835a-b304-11e5-87f9-81e021ef9fbb.png)
