### ISSUE TITLE
Usersnap Feedback - It would have been really useful to see file size and last date of update [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#319]
**Sender**: asba.tasneem@duke.edu
**Comment**: It would have been really useful to see file size and last date of update in the folder menu. 

I am trying to assess whether DDS is useful for file/content sharing for project management use case. I would like it to provide at the very minimum what I get from Duke Box or Network Drive (P drive) or even SharePoint. If not, what is the incentive for me to use DDS and spend more time doing simple tasks like "find the most recent version of a relevant file --> open --> edit  --> save in it's original location". 

Thanks guys! 
Asba
[Open #63 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/63)

![Usersnap Feedback - It would have been really useful to see file size and last date of update (...)](https://usersnappublic.s3.amazonaws.com/2016-04-25/18-52/1b56425f-9264-4363-be34-84805a616d29.png)

**Browser**: Chrome 49 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/project/58721955-f210-42a1-85c2-75f02f55559b](https://dataservice.duke.edu/#/project/58721955-f210-42a1-85c2-75f02f55559b)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 955

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I'm following up with Asba on this. I think it's probably good feedback but what I see is a screenshot of the project root. She says she wants to "see file size and last date of update in the folder menu". I'm not sure what she's asking for here. The file size and date of last update is available in the file view. Is she asking that it be displayed in the list item (project children/folder children lists) as well? I could see this being a "nice to have" feature but I want to make sure I'm understanding what she's looking for first. I think a last updated and file size would probably be way more useful than the 'id'
 here ![screen shot 2016-04-25 at 10 05 12 am](https://cloud.githubusercontent.com/assets/10411174/14792140/d4ea25b0-0acd-11e6-85d1-f56a9be6e882.png)

**Comment by jonturneratduke** [comment]
"She" :)  Asba is a project manager here in our department and she's trying her darnedest to use DS. :)

At the moment she's looking to display this info in the list, as well. And yes, in project root and children folder views.

## I think seeing the size in the folder list would be useful.

Jon

**Comment by caseychoiniere** [comment]
@jonturneratduke Thanks, I updated my comment to reflect "She" and not "He" :) I have a gender neutral name myself so I understand people getting this wrong sometimes. I also think it could be useful and wonder if 'id' is superfluous in the list item anyways. Perhaps this space would better be used for 'file size' and 'last updated date'? @erichhuang Any thoughts?

**Comment by jonturneratduke** [comment]
I think ID is much less useful/meaningful to users vs. the development team. That is prime real estate.
