### ISSUE TITLE
Hovering pointer over pink "Upload" button should give tool tip "Upload File"

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#32]

**Comment by caseychoiniere** [comment]
I have tooltips in place, but I see now there is a bug with them. They don't initialize until the page refreshes. I think this is an issue with MDL. Apparently most of the MDL components are incompatible with React. I'll just replace this MDL component.

**Comment by caseychoiniere** [comment]
Tooltips in place on upload and download buttons
