### ISSUE TITLE
Sent to home screen when opening a project specific URL when not logged in.

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service-portal#325]
If I am not logged in and try to go to a link like this:
https://dataservice.duke.edu/#/project/4f3d600d-8fd9-4851-88ad-07b2fc889784
I get the login button screen.
After clicking login and entering user/password I am sent to the home screen.
I expected to go to the project screen for 4f3d600d-8fd9-4851-88ad-07b2fc889784.
Thanks.

**Comment by dleehr** [comment]
Just for some context, we mentioned this yesterday in a meeting with @jonturneratduke and @mgardnerpsu.

**Comment by caseychoiniere** [comment]
Fixed.
