### ISSUE TITLE
When one logs out of Portal, should dump to a generic DDS intro page [Login/Logout]

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#33]
Obviously, we'll need to create an "intro to DDS" type page to do this

**Comment by caseychoiniere** [comment]
What would you want on this page? Something similar to this?
![screen shot 2016-01-26 at 11 23 28 am](https://cloud.githubusercontent.com/assets/10411174/12592186/2f81d01c-c420-11e5-8bce-b271ce311400.png)

**Comment by caseychoiniere** [comment]
Or simply the top portion with a description of the service, a logo and a login button that logs you in? I'll need some approved text for the description.
![screen shot 2016-01-26 at 11 30 50 am](https://cloud.githubusercontent.com/assets/10411174/12592223/65131312-c420-11e5-962b-5585dec673b4.png)

**Comment by erichhuang** [comment]
Yeah, and then we'd make sure `/index` doesn't redirect to `/portal` once we do this. I'll mock up a page for you to work off of.

**Comment by erichhuang** [comment]
For now though, let's dump to the `Login` screen
