### ISSUE TITLE
Usersnap Feedback - "copy key to clipboard" doesn't copy value.

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#343]
**Sender**: kevin.wiehe@duke.edu
**Comment**: "copy key to clipboard" doesn't copy value. 
[Open #67 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/67)

![Usersnap Feedback - "copy key to clipboard" doesn't copy value.](https://usersnappublic.s3.amazonaws.com/2016-05-25/19-20/d4487480-0b79-4c11-8897-186a630363fd.png)

**Browser**: Safari 9 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/agent/20593f1b-3ded-4df5-b8bf-0a92c4f655a5](https://dataservice.duke.edu/#/agent/20593f1b-3ded-4df5-b8bf-0a92c4f655a5)
**Screen size**: 1920 x 1080 **Browser size**: 894 x 993

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Safari doesn't have browser support for document.execCommand('copy') yet. So no copying to the clipboard with javascript. Will implement a user alert if they are using Safari that will let them know to manually copy the key.
