### ISSUE TITLE
Usersnap Feedback - where is a tutorial?  I have tried everyway possible to add a project memb[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#346]
**Comment**: where is a tutorial?  I have tried everyway possible to add a project member but continue to get a message saying user cannot be added or found - but there is no help or guide or details about how to add somone.  This is not a very intuitive system - there should be some more help screens or hints
[Open #69 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/69)

![Usersnap Feedback - where is a tutorial?  I have tried everyway possible to add a project memb(...)](https://usersnappublic.s3.amazonaws.com/2016-05-31/22-14/28db01ea-6964-47bb-be04-ea0a8f716bfb.png)

**Browser**: Chrome 50 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/project/e16337b6-41b2-4b05-82f2-9aade20a1448](https://dataservice.duke.edu/#/project/e16337b6-41b2-4b05-82f2-9aade20a1448)
**Screen size**: 1920 x 1080 **Browser size**: 1583 x 747

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke Looks like this user is pretty frustrated. They left their comment as anonymous though so I can't respond to their request. Looking at the screenshot it looks like the name in the "created by" section is Jeyalakshmi Ramanthan. Is it possible to track them down and help them through this? I'm guessing they're trying to add someone who hasn't been granted access to DDS.

**Comment by caseychoiniere** [comment]
And for posterity's sake, maybe this should be in the help guide

**Comment by erichhuang** [comment]
Yeah, quick search shows she’s some IT person in DCRI. I guess the one problem with random users jumping in is that they have no idea of the roadmap, so yes, right now, Box is better. We actually should think sooner than later about putting a public webpage/blog about what DukeDS is about.

E

**Comment by jonturneratduke** [comment]
## Thanks, everybody. I'll reach out to Jeyalakshmi to ask how I can help.

Jon
