### ISSUE TITLE
Usersnap Feedback - why is help grayed out?  It took a few minutes to figure out that the 3 ra[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#347]
**Comment**: why is help grayed out?  It took a few minutes to figure out that the 3 random dots are actually the menu.  not very user friendly and with no help screen - not very inviting to use.  Box is better
[Open #70 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/70)

![Usersnap Feedback - why is help grayed out?  It took a few minutes to figure out that the 3 ra(...)](https://usersnappublic.s3.amazonaws.com/2016-05-31/22-15/d22e556f-b5b4-4249-b554-2d8bb65749f9.png)

**Browser**: Chrome 50 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/project/e16337b6-41b2-4b05-82f2-9aade20a1448](https://dataservice.duke.edu/#/project/e16337b6-41b2-4b05-82f2-9aade20a1448)
**Screen size**: 1920 x 1080 **Browser size**: 1583 x 747

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Should I remove these items from the menu until they function? Wasn't worried about it for Alpha release but seems like it might be a good idea. If they don't go anywhere they shouldn't even be there.

**Comment by caseychoiniere** [comment]
Maybe at some point we should consider a "tour" plugin for new users. Something like this http://gilbarbara.github.io/react-joyride/

**Comment by jonturneratduke** [comment]
Too bad anonymous didn't leave more info - I'd like to follow up.
Regardless, there are a couple things here. The first is the "three dash" menu. I've seen pretty consistently that users fail to recognize that as a menu. However, once they've seen it, it's remembered as such but maybe there's a way to make it more obvious?

For the greyed-out menu items, they are acting as placeholders so yes, I think they should probably be removed until we're ready to implement something or add content. I do think we have "terms and conditions" content though (the splash screen). Could we keep that option and show the splash screen?

**Comment by jonturneratduke** [comment]
Yes, absolutely! I love that idea!

**Comment by caseychoiniere** [comment]
Interesting that the 3 dot menu creates so much confusion. It's practically become a web standard. In fact Box uses the 3 dot menu in several places throughout their web app. We certainly could show the splash screen, once we build it ;) Until then we can just remove these items from the menu.

**Comment by erichhuang** [comment]
I agree. Though I will say that people seem to grok the three line icon better. 

E

erich s. huang, md-phd
https://calendly.com/erich-huang
