### ISSUE TITLE
Usersnap Feedback - Can not down load folders

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#349]
**Sender**: leonard.santoro@duke.edu
**Comment**: Can not down load folders
[Open #71 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/71)

![Usersnap Feedback - Can not down load folders](https://usersnappublic.s3.amazonaws.com/2016-06-07/15-05/91f44427-9360-4bb6-8a08-a4db186769f1.png)

**Browser**: Microsoft Internet Explorer 11 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/project/da7e3d23-c4a5-4b5c-becf-8fd3821054a3](https://dataservice.duke.edu/#/project/da7e3d23-c4a5-4b5c-becf-8fd3821054a3)
**Screen size**: 1920 x 1200 **Browser size**: 1391 x 905

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Until the service supports this, it's a no-go. Right now DDS just returns a download URL for each file which is then handled by the browser. Would need an endpoint that would handle folder downloads. Should this be an issue or feature request in DDS?
