### ISSUE TITLE
Getting "Error:Error: Bad Request" with file upload

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#36]
And then the web app becomes unresponsive (beachballs in both Safari and Chrome)
![alt tag](https://dl.dropboxusercontent.com/s/ngq5a9ckdge0lfz/Screenshot%202016-01-04%2016.09.49.png)

This is for `commit 9b35d4ff83b4878177e362cd1d80d72c524111bd`

**Comment by caseychoiniere** [comment]
When I run locally it works fine but in production part of the payload is missing when my create file action runs. It's the parent payload. It should be
`parent: {kind: "dds-project", id: "13080000-bbdc-4ba7-bae8-6a843a977d09"}
upload: {id: "04d52f95-221e-4b83-8a9c-00bd51881871"}`
but instead on production it's always empty like
`parent: {}
upload: {id: "04d52f95-221e-4b83-8a9c-00bd51881871"}`
Working on it now.

**Comment by caseychoiniere** [comment]
Found and fixed issue. PR created for Darin to review and build.
