### ISSUE TITLE
Usersnap Feedback - I like the recursiveness too: one other suggestion is having the "file pat[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#387]
**Sender**: erich.huang@duke.edu
**Comment**: I like the recursiveness too: one other suggestion is having the "file paths" show up. For instance "temp_10B_fileFoo" is inside a folder and it'd be nice to be able to see that.
[Open #76 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/76)

<a href='https://usersnappublic.s3.amazonaws.com/2016-08-02/20-32/a9dfac1a-e751-4351-8807-acbab4a2907b.png'>![Usersnap Feedback - I like the recursiveness too: one other suggestion is having the "file pat(...)](https://usersnappublic.s3.amazonaws.com/2016-08-02/20-32/8aab6523-e390-4075-9835-d0611960aa23.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-08-02/20-32/a9dfac1a-e751-4351-8807-acbab4a2907b.png'>Download original image</a>

**Browser**: Safari 10 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/#/project/0c2916df-dce9-4cc3-9904-e9c71e99ac9d](https://dev.dataservice.duke.edu/#/project/0c2916df-dce9-4cc3-9904-e9c71e99ac9d)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
That's a nice idea. I think this would require a change to the service though, otherwise too much heavy lifting on the client. Perhaps with Elasticsearch this can be implemented?
