### ISSUE TITLE
Downloading filetype

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#41]
When downloading this file: https://dev.dataservice.duke.edu/portal/#/file/63206329-958b-4dea-b67b-c12a5c332a32 (you should have access)

It doesn't preserve the filetype (it's an MP4 video). If I reappend `.mp4`, it still won't open as an MP4.

On the other hand, this screenshot (PNG): https://dev.dataservice.duke.edu/portal/#/file/1f986482-6051-43b7-b5f8-a7e252bf56ee

Seems to work

**Comment by erichhuang** [comment]
Actually, this looks like it may be an issue with reassembling the chunks. If a file is < 5Mb, things seem to work. If the file is > 5Mb (i.e. Swift uses 5Mb chunks) it fails.

**Comment by Donmurry** [comment]
I'm noticing this issue with the reassembling of an mp3.  I am able to append .mp3 and get the file to play, but the song is played in reverse order.  At 0:00 the last third or fourth of the song is playing.  Once that section plays, it progresses till the beginning of the song plays. This particular song was >5Mb.

**Comment by caseychoiniere** [comment]
Is this an issue that should be raised in DDS? The client never actually reassembles the file. It simply hashes the whole file, splits the file, hashes each chunk, gets a pre-signed url for each chunk, uploads each chunk to swift based on the chunk number and then when all chunks are completed it calls `uploads/uploadId/complete` and then based on that success does a POST to create the file.

**Comment by dmlond** [comment]
just pushed a fix to DDS develop. It was DDS bug (Casey was right). Test it out with your favorite songs. I will leave this issue open, but someone should probably close it.

**Comment by Donmurry** [comment]
Retested with another .mp3 and also tried with an appended .mp4 extension on a video file and the file played.

**Comment by erichhuang** [comment]
Resolved.
