### ISSUE TITLE
Files should download with their filenames, as opposed to GUID

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#42]
Also, should remember the file extension.

![screenshot 2016-01-05 11 55 15](https://cloud.githubusercontent.com/assets/386675/12121425/456b5214-b3a3-11e5-83e8-cb688ee851b6.png)

**Comment by caseychoiniere** [comment]
Looks like this needs to be done on the server. A header needs to be set on the response that includes a content-type and content-disposition that includes the file name. Example: `Content-Type: application/pdf
Content-Disposition: inline; filename="filename.pdf"`
http://stackoverflow.com/questions/3102226/how-to-set-name-of-file-downloaded-from-browser
http://stackoverflow.com/questions/6293893/how-to-force-files-to-open-in-browser-instead-of-download-pdf

This issue should be moved to DDS?

**Comment by dmlond** [comment]
we need to research this. It is not technically DDS either.  DDS gives the portal (or client in general) a temporary url to the swift service.  The client then calls the swift service to download the file. I will dig into the swift documentation to see how it is possible to make a static-large-object request provide these headers

**Comment by mgardnerpsu** [comment]
can this information be provided in the "http_headers" array that is returned from the /file/{id}/url endpoint?  we have this info in the postgres metadata for the file/upload - then casey would inject into the request header before GET on temporary swift URL?

**Comment by dmann** [comment]
@dmlond will have to confirm, but it looks like we should be able to tack a &filename=foo.txt onto the generated temp url:

http://docs.openstack.org/developer/swift/api/temporary_url_middleware.html#temporary-url-format

**Comment by dmlond** [comment]
actually, It may actually be a DDS problem. I think we need to set the content-type and content-disposition on the static large object that we create when the upload is completed. I will research.

**Comment by caseychoiniere** [comment]
Might be useful info
http://tools.ietf.org/html/rfc6266 

Section 4.2

**Comment by erichhuang** [comment]
Resolved.
