### ISSUE TITLE
Usersnap Feedback - I'm thinking we have tags in "our" shade of blue as opposed to green, try [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#424]
**Sender**: erich.huang@duke.edu
**Comment**: I'm thinking we have tags in "our" shade of blue as opposed to green, try boldface characters, have the tag icon in the same pink shade us upload/download?
[Open #78 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/78)

<a href='https://usersnappublic.s3.amazonaws.com/2016-08-19/02-24/e7427979-7700-49ff-8f94-990c3bc2fdcd.png'>![Usersnap Feedback - I'm thinking we have tags in "our" shade of blue as opposed to green, try (...)](https://usersnappublic.s3.amazonaws.com/2016-08-19/02-24/c4ef32aa-aaed-4245-9671-b757ec08914d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-08-19/02-24/e7427979-7700-49ff-8f94-990c3bc2fdcd.png'>Download original image</a>

**Browser**: Safari 10 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/#/file/a931b05a-1cea-48dd-becf-00b2af2d8ebf](https://dev.dataservice.duke.edu/#/file/a931b05a-1cea-48dd-becf-00b2af2d8ebf)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@erichhuang I made the changes you requested. Let me know if it's not what you're after.

**Comment by erichhuang** [comment]
Yes. I like.
