### ISSUE TITLE
Usersnap Feedback - At some point, I'd like to figure out a way for someone to know, without h[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#427]
**Sender**: erich.huang@duke.edu
**Comment**: At some point, I'd like to figure out a way for someone to know, without having to navigate back up to the Project level, what their Role is.
[Open #79 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/79)

<a href='https://usersnappublic.s3.amazonaws.com/2016-08-23/21-40/d688de6d-f743-4841-8e2b-bf2df8a4e70f.png'>![Usersnap Feedback - At some point, I'd like to figure out a way for someone to know, without h(...)](https://usersnappublic.s3.amazonaws.com/2016-08-23/21-40/ef81c245-04a1-4104-a101-eb24b53a7a8e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-08-23/21-40/d688de6d-f743-4841-8e2b-bf2df8a4e70f.png'>Download original image</a>

**Browser**: Safari 10 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/#/file/16dda091-b4bb-43e5-ad58-834ce81c4e06](https://dev.dataservice.duke.edu/#/file/16dda091-b4bb-43e5-ad58-834ce81c4e06)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 712

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
added to the user details dropdown
