### ISSUE TITLE
Usersnap Feedback - I could swear that autocomplete worked on last names in the past, but perh[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#428]
**Sender**: erich.huang@duke.edu
**Comment**: I could swear that autocomplete worked on last names in the past, but perhaps I missed this? Is it do-able?
[Open #80 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/80)

<a href='https://usersnappublic.s3.amazonaws.com/2016-08-26/16-26/b5ef44a1-2a93-4f4b-8d87-fac5d742e376.png'>![Usersnap Feedback - I could swear that autocomplete worked on last names in the past, but perh(...)](https://usersnappublic.s3.amazonaws.com/2016-08-26/16-26/847a5388-bacc-4ab1-aa00-6656d9dd8caf.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-08-26/16-26/b5ef44a1-2a93-4f4b-8d87-fac5d742e376.png'>Download original image</a>

**Browser**: Safari 10 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/project/6ff745aa-609f-418a-ae5e-bb23be25eb90](https://dataservice.duke.edu/#/project/6ff745aa-609f-418a-ae5e-bb23be25eb90)
**Screen size**: 1280 x 800 **Browser size**: 1010 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Probably. Let me look into it

**Comment by caseychoiniere** [comment]
Ok, there's actually a bug in the Autocomplete filter that is used in Material-UI. They've fixed this in a later version of Material-UI but because there are quite a few breaking changes that will need to be addressed when updating to this newer version I'm going to delay this fix  until I have some time scheduled for this.

**Comment by caseychoiniere** [comment]
Found a way to fix it for now. Figured it out while working an a file picker autocomplete for provenance. Two birds with one stone...
