### ISSUE TITLE
Usersnap Feedback - The magenta paperclip "upload" button doesn't bring up the file selector. [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#433]
**Sender**: jonathan.turner@duke.edu
**Comment**: The magenta paperclip "upload" button doesn't bring up the file selector. Seems to be a Firefox-only issue.
[Open #81 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/81)

<a href='https://usersnappublic.s3.amazonaws.com/2016-08-26/22-48/e0e09e42-7ef5-4b37-8485-4bc85dcdce20.png'>![Usersnap Feedback - The magenta paperclip "upload" button doesn't bring up the file selector. (...)](https://usersnappublic.s3.amazonaws.com/2016-08-26/22-48/111340fd-5d07-44f3-a557-c497aa2541a3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-08-26/22-48/e0e09e42-7ef5-4b37-8485-4bc85dcdce20.png'>Download original image</a>

**Browser**: Firefox 48 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/#/project/e483e735-ce2c-434c-9c72-4bff035c9406](https://dev.dataservice.duke.edu/#/project/e483e735-ce2c-434c-9c72-4bff035c9406)
**Screen size**: 1680 x 1050 **Browser size**: 1536 x 893

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Nice catch. This was a byproduct of an IE hack/fix. Fixed it.
