### ISSUE TITLE
Usersnap Feedback - Consider "thinning" the top blue bar, centering the DukeDS and hamburger, [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#439]
**Sender**: erich.huang@duke.edu
**Comment**: Consider "thinning" the top blue bar, centering the DukeDS and hamburger, moving search window left
[Open #83 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/83)

<a href='https://usersnappublic.s3.amazonaws.com/2016-09-08/20-06/0a1a904b-74fe-48db-a386-137b4904269a.png'>![Usersnap Feedback - Consider "thinning" the top blue bar, centering the DukeDS and hamburger, (...)](https://usersnappublic.s3.amazonaws.com/2016-09-08/20-06/72c6fd4b-36bf-45e8-ba95-23d8c5ef641b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-09-08/20-06/0a1a904b-74fe-48db-a386-137b4904269a.png'>Download original image</a>

**Browser**: Safari 10 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/#/project/92040a3e-f1be-45dd-aaf9-a0fc8531a43d](https://dev.dataservice.duke.edu/#/project/92040a3e-f1be-45dd-aaf9-a0fc8531a43d)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 689

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I thinned the header and centered the logo. The search field doesn't look well or play well when it's pushed to the left of the header so I kept it in the middle.
