### ISSUE TITLE
Usersnap Feedback - After creating a tag, the text field is not cleared. This is a known bug w[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#443]
**Sender**: caseychoiniere@gmail.com
**Comment**: After creating a tag, the text field is not cleared. This is a known bug with the Autocomplete feature in Material-UI. There's a fix for this in a later version but in order to update to that version there are a lot of breaking changes involved. So as a workaround, I made it so that the field value is highlighted instead. 
[Open #85 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/85)
**Notes**:
- (1) After creating a tag, the text field is not cleared. This is a known bug with the Autocomplete feature in Material-UI. There's a fix for this in a later version but in order to update to that version there are a lot of breaking changes involved. So as a workaround, I made it so that the field value is highlighted instead.

<a href='https://usersnappublic.s3.amazonaws.com/2016-09-09/17-20/eb25f603-7acf-4b38-afd6-aacfe6ccfb09.png'>![Usersnap Feedback - After creating a tag, the text field is not cleared. This is a known bug w(...)](https://usersnappublic.s3.amazonaws.com/2016-09-09/17-20/2e2ee6b7-c552-4a4d-92cb-af4bb0198564.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-09-09/17-20/eb25f603-7acf-4b38-afd6-aacfe6ccfb09.png'>Download original image</a>

**Browser**: Chrome 52 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/#/file/beb9f45a-c662-4f45-ab56-93337f18ad92](https://dev.dataservice.duke.edu/#/file/beb9f45a-c662-4f45-ab56-93337f18ad92)
**Screen size**: 1920 x 1080 **Browser size**: 1764 x 983

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
fixed
