### ISSUE TITLE
Usersnap Feedback - @matt I'm thinking we should revisit the API on restricting a File "using" [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#462]
**Sender**: erich.huang@duke.edu
**Comment**: @matt I'm thinking we should revisit the API on restricting a File "using" another File. Or am I abusing the W3C spec?
[Open #89 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/89)

<a href='https://usersnappublic.s3.amazonaws.com/2016-09-22/15-46/35492afd-89df-438d-8876-0cd1e3fc651b.png'>![Usersnap Feedback - @matt I'm thinking we should revisit the API on restricting a File "using" (...)](https://usersnappublic.s3.amazonaws.com/2016-09-22/15-46/7207f116-7c71-4632-827a-dd7fb5e825f3.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-09-22/15-46/35492afd-89df-438d-8876-0cd1e3fc651b.png'>Download original image</a>

**Browser**: Safari 10 (Macintosh)
**Referer**: [https://dev.dataservice.duke.edu/#/file/942cb8cc-c35f-4cd7-8c2f-e3406558f014](https://dev.dataservice.duke.edu/#/file/942cb8cc-c35f-4cd7-8c2f-e3406558f014)
**Screen size**: 2560 x 1440 **Browser size**: 1324 x 1352

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I've migrated this issue to the API repo instead.
