### ISSUE TITLE
Folder/file search not working  [Search]

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service-portal#47]
File search only works after I reload the browser page, otherwise it does not filter list.

<img width="1440" alt="screen shot 2016-01-06 at 1 22 49 pm" src="https://cloud.githubusercontent.com/assets/2471755/12150665/0e774020-b479-11e5-9b4e-081ce4fc1fc7.png">

**Comment by caseychoiniere** [comment]
See issue #48 
Search should be recursive
