### ISSUE TITLE
Usersnap Feedback - logo on splash screen - broken link?

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#472]
**Sender**: jonathan.turner@duke.edu
**Comment**: logo on splash screen - broken link?
[Open #90 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/90)
**Notes**:
- (1) broken link to logo on splash screen

<a href='https://usersnappublic.s3.amazonaws.com/2016-09-30/16-29/5f2a0772-d95a-4430-a73d-53820d3b4b10.png'>![Usersnap Feedback - logo on splash screen - broken link?](https://usersnappublic.s3.amazonaws.com/2016-09-30/16-29/6da255b3-f434-4dde-bfb8-36b71a9327d2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-09-30/16-29/5f2a0772-d95a-4430-a73d-53820d3b4b10.png'>Download original image</a>

**Browser**: Firefox 49 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/portal/#/login](https://dev.dataservice.duke.edu/portal/#/login)
**Screen size**: 1680 x 1050 **Browser size**: 906 x 658

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jonturneratduke** [comment]
weird. looks like it was a transient thing. seems to be okay now.

**Comment by caseychoiniere** [comment]
@jonturneratduke Yes, I talked with Darin London about this a while back. `/portal/#/` breaks the path to image assets for some reason. Need to figure out if this is an issue with the way that the portal is deployed. Images  don't reside in `https://dev.dataservice.duke.edu/portal/images/` which is the request that's being made. So, if you use `https://dev.dataservice.duke.edu/portal/#/login` the image will be broken. If you use `https://dev.dataservice.duke.edu/#/login` the images are served fine.

**Comment by caseychoiniere** [comment]
I guess DDS is omitting the `#` when requesting the image asset. I think this is something that needs to be configured on the rails end. 
@dmlond ?
