### ISSUE TITLE
Usersnap Feedback - attempting to add myself to project I created, with lower permissions leve[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#473]
**Sender**: jonathan.turner@duke.edu
**Comment**: attempting to add myself to project I created, with lower permissions level than Admin/Owner -- should this be allowed? If so, the red error messages don't seem to apply. (field is supplied, project role is selected -- the actual problem is I've tried to add myself). Soln to filter oneself from the dropdown list of names?
[Open #91 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/91)

<a href='https://usersnappublic.s3.amazonaws.com/2016-09-30/16-32/32976b5c-2bc0-40d7-85a7-81c3c098cbb9.png'>![Usersnap Feedback - attempting to add myself to project I created, with lower permissions leve(...)](https://usersnappublic.s3.amazonaws.com/2016-09-30/16-32/bdeb0542-a106-48b6-873b-dc157c57b648.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-09-30/16-32/32976b5c-2bc0-40d7-85a7-81c3c098cbb9.png'>Download original image</a>

**Browser**: Firefox 49 (OS X El Capitan)
**Referer**: [https://dev.dataservice.duke.edu/#/project/e5ed93fc-ce46-4411-a535-4d2c18321ee4](https://dev.dataservice.duke.edu/#/project/e5ed93fc-ce46-4411-a535-4d2c18321ee4)
**Screen size**: 1680 x 1050 **Browser size**: 1071 x 840

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
This is what I get. Validation says "You can't add yourself or change your own role"
Must have been a weird condition...
![screen shot 2016-09-30 at 8 08 13 am](https://cloud.githubusercontent.com/assets/10411174/18996421/24daeab2-86e5-11e6-9fc9-c9e798b20626.png)

**Comment by dmlond** [comment]
Currently, the system does not allow a user to remove their admin role from a project, which also prevents them demoting themselves. Their role must be removed or changed by another project admin. This is a simple way to prevent the orphaning of a project. Otherwise we have to make logic in the system which checks to see if there is another admin before allowing a user to remove their admin role.

**Comment by caseychoiniere** [comment]
Yep, and I validate the form to prevent people from having to deal with the error that would result.
