### ISSUE TITLE
Usersnap Feedback - I would be nice to have previous tags I create to appear in the for my selection

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#480]
**Comment**: I would be nice to have previous tags I create to appear in the for my selection
[Open #93 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/93)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-06/22-09/bfadc76f-9b46-4332-a0be-2d3b3078dd25.png'>![Usersnap Feedback - I would be nice to have previous tags I create to appear in the for my selection](https://usersnappublic.s3.amazonaws.com/2016-10-06/22-09/b786d97c-4ad3-4c94-8c19-3b2c023bc4e9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-06/22-09/bfadc76f-9b46-4332-a0be-2d3b3078dd25.png'>Download original image</a>

**Browser**: Chrome 53 (Windows 7)
**Referer**: [https://dev.dataservice.duke.edu/#/folder/ce15320a-9430-4e0d-bb99-7bf2f51cc94c](https://dev.dataservice.duke.edu/#/folder/ce15320a-9430-4e0d-bb99-7bf2f51cc94c)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 762

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Good call. Not sure why I left this out on the upload manager...
