### ISSUE TITLE
Usersnap Feedback - It would me nice if the there was a file browser to select objects for pro[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#481]
**Comment**: It would me nice if the there was a file browser to select objects for provenance
[Open #94 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/94)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-06/22-12/24b5c500-c499-4f13-8c71-85bf9ca697ec.png'>![Usersnap Feedback - It would me nice if the there was a file browser to select objects for pro(...)](https://usersnappublic.s3.amazonaws.com/2016-10-06/22-12/5047d62b-b5fb-4239-b82a-ec1a1a86a200.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-06/22-12/24b5c500-c499-4f13-8c71-85bf9ca697ec.png'>Download original image</a>

**Browser**: Chrome 53 (Windows 7)
**Referer**: [https://dev.dataservice.duke.edu/#/file/9619c8b9-166a-4844-ad32-c148430908c5](https://dev.dataservice.duke.edu/#/file/9619c8b9-166a-4844-ad32-c148430908c5)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 762

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Are you referring to a full file picker that shows folder hierarchy etc? If so, this is a complex feature request and would be used in more places than just provenance. I believe this should be on the roadmap at some point now that global object search is implemented. Keep in mind that this component would be a high effort undertaking and would likely take several weeks (3+) to build.

**Comment by caseychoiniere** [comment]
Chet is working on this
