### ISSUE TITLE
Handle Provenance Nodes that have no properties object

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#482]
From docs: If the user does not have visibilty to a node in the resulting graph, the properties attribute for that node will be a partial resource containing: kind, id, and is_deleted. 

Currently the graph relies on information in the properties object to handle a lot of the logic involved in the editor. A node should show on the graph if user has no visibility but it needs to be disabled from all events and editing etc.

In order to allow me to test this case, I'll need someone to create a project (Project A) and upload several files and file versions. Then grant me access so it shows in my project list. I can then add files from that project into a provenance graph in one of my projects (Project B). Then my access needs to be revoked from the Project A. That way I can work with files that I don't have visibility to. 

@jonturneratduke Can you help me out with this?

**Comment by jonturneratduke** [comment]
Project A is added with two files, and each has a version. ping me when you're ready for me to revoke access.

**Comment by caseychoiniere** [comment]
Thanks Jon! You can revoke my access now.
