### ISSUE TITLE
Usersnap Feedback - When i tried to add a relation, I get the following error.. here were my s[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#483]
**Comment**: When i tried to add a relation, I get the following error.. here were my steps:
1) Added two file
2) Clicked the "Used by" activity
3) Selected a file and did a drag to create a relation
4) The 404 error appeard
[Open #95 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/95)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-06/22-34/2f4ee330-5efa-45fd-a674-ce579592959f.png'>![Usersnap Feedback - When i tried to add a relation, I get the following error.. here were my s(...)](https://usersnappublic.s3.amazonaws.com/2016-10-06/22-34/57778933-816f-41a6-8412-600c98b2748b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-06/22-34/2f4ee330-5efa-45fd-a674-ce579592959f.png'>Download original image</a>

**Browser**: Chrome 53 (Windows 7)
**Referer**: [https://dev.dataservice.duke.edu/#/notFound](https://dev.dataservice.duke.edu/#/notFound)
**Screen size**: 1600 x 900 **Browser size**: 1600 x 762

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Added node kind is `dds-file` and editor expects `dds-file-version`. I'll fix this asap. Thanks Jon!

**Comment by caseychoiniere** [comment]
Fixed on next build.
