### ISSUE TITLE
Usersnap Feedback - Tried to upload 10 fies @ ~35BK and added three tags to these files and sy[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#506]
**Sender**: james.fayson@duke.edu
**Comment**: Tried to upload 10 fies @ ~35BK and added three tags to these files and system hangs
[Open #96 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/96)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/18-51/8d417d81-f9b4-4c49-a561-c8bf411b8d66.png'>![Usersnap Feedback - Tried to upload 10 fies @ ~35BK and added three tags to these files and sy(...)](https://usersnappublic.s3.amazonaws.com/2016-10-25/18-51/a4809b83-71b3-4c50-b043-eb3fa588918c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/18-51/8d417d81-f9b4-4c49-a561-c8bf411b8d66.png'>Download original image</a>

**Browser**: Chrome 54 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/folder/4b7105fa-2add-4080-bcbf-c4e571a6436b](https://dataservice.duke.edu/#/folder/4b7105fa-2add-4080-bcbf-c4e571a6436b)
**Screen size**: 1280 x 720 **Browser size**: 1707 x 789

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I'm seeing an intermittent failure with CryptoJS in the web worker script. Trying to find a solution now. It's an issue with the library itself so might need to look at a different library.
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-bugs/X0--X8b3qTc

**Comment by caseychoiniere** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=252492#c21

**Comment by caseychoiniere** [comment]
This is a Chrome bug. It only happens with files of certain sizes. Happens between ~127kb - ~262kb range

**Comment by caseychoiniere** [comment]
https://code.google.com/archive/p/crypto-js/issues/68
