### ISSUE TITLE
Don't see Usersnap in Prod

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#508]
I'm connected from an outside TimeWarnerCable wifi network and am not seeing the Usersnap icon on prod. Is it showing up for everyone else?

**Comment by caseychoiniere** [comment]
I see it here

**Comment by erichhuang** [comment]
It may be TWC is somehow stripping it out. We'll need to research a bit more.

**Comment by jonturneratduke** [comment]
I’ll hit it from my TWC account at home tonight and let you guys know.

**Comment by jonturneratduke** [comment]
Possibly related, but I tried to enter a usersnap issue yesterday on UATest, and usersnap threw a license-key error: "referrer not valid for this API key". Could that be a case of the prod key on the uaTest tier (or vice versa)?
<img width="556" alt="screen shot 2016-10-25 at 2 09 23 pm" src="https://cloud.githubusercontent.com/assets/11540881/19698310/c9178302-9abc-11e6-831c-f74ef04f1216.png">

**Comment by caseychoiniere** [comment]
Still an issue?
