### ISSUE TITLE
Usersnap Feedback - it looks like it is sending a blank body in the request to the backend

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#509]
**Sender**: None
**Comment**: it looks like it is sending a blank body in the request to the backend
[Open #97 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/97)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/19-40/d1258fe9-233f-4ba7-ad4b-cbfeb4b364a0.png'>![Usersnap Feedback - it looks like it is sending a blank body in the request to the backend](https://usersnappublic.s3.amazonaws.com/2016-10-25/19-40/3bd5e510-540f-4491-bf56-f7d946d6df42.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/19-40/d1258fe9-233f-4ba7-ad4b-cbfeb4b364a0.png'>Download original image</a>

**Browser**: Chrome 53 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/file/5eb4f9a1-c937-4ab2-8c27-886e47314116](https://dataservice.duke.edu/#/file/5eb4f9a1-c937-4ab2-8c27-886e47314116)
**Screen size**: 1440 x 900 **Browser size**: 1440 x 775

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I'm sorry. Can you elaborate on this? Which request are you referring to?

**Comment by dmlond** [comment]
sorry, this is my first usersnap submission. I didnt realize that the first entry would be stripped out, or something. It should say, "I tried to create a tag but it didnt work" before "it looks like..." :)

I tried to append a tag on the file in the file viewer. I opened the network traffic in the javascript console when I hit 'append', and the payload to the endpoint was
{tags: []}.
It got a 201 response code :)

**Comment by caseychoiniere** [comment]
Hmmm, I don't see that. I have the request body as `{tags:[{tag1},{ tag2}]}`

**Comment by dmlond** [comment]
I just tried it again, and I still get the same empty payload? I tried to hard-reload first to make sure I didnt have some kind of weird javascript library or something. Not sure what else to try. I am using Chrome.

**Comment by caseychoiniere** [comment]
![screen shot 2016-10-25 at 10 56 08 am](https://cloud.githubusercontent.com/assets/10411174/19697816/cf54e6c6-9aa1-11e6-9c57-597bf62313df.png)

**Comment by caseychoiniere** [comment]
I see the issue. It's actually a validation error. If you type a tag into the text field and don't hit enter or the "+" icon it doesn't actually add t to the list but my validation is still allowing the form to be submitted. Thanks Darin. Good catch.
