### ISSUE TITLE
Usersnap Feedback - The box logo is not displaying

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#510]
**Sender**: None
**Comment**: The box logo is not displaying
[Open #98 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/98)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/20-30/104b8b71-5e9e-4f6b-a4a4-274ab9f0de57.png'>![Usersnap Feedback - The box logo is not displaying](https://usersnappublic.s3.amazonaws.com/2016-10-25/20-30/97cc9728-d9e3-47f0-8d51-9298ab4abe3b.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/20-30/104b8b71-5e9e-4f6b-a4a4-274ab9f0de57.png'>Download original image</a>

**Browser**: Chrome 54 (Mac OS X Yosemite)
**Referer**: [https://dataservice.duke.edu/portal/#/login](https://dataservice.duke.edu/portal/#/login)
**Screen size**: 1280 x 800 **Browser size**: 1213 x 589

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
This issue has already been opened here  https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/issues/472
I did my best to debug it and offered some thoughts as to whats causing it but never received a response from anyone. It seems to have something to do with how the rails app is asking for assets.
