### ISSUE TITLE
Usersnap Feedback - When I log in, I am taken to the privacy policy page. Here's my chain of e[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#511]
**Sender**: None
**Comment**: When I log in, I am taken to the privacy policy page.
Here's my chain of events:
open main page
click privacy policy.
click "back arrow" on browser toolbar
click log in button
authenticate through duke shibboleth
privacy page is loaded.

[Open #99 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/99)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/20-32/71306f48-dbeb-4df9-abc5-fbe9c12bc7d2.png'>![Usersnap Feedback - When I log in, I am taken to the privacy policy page. Here's my chain of e(...)](https://usersnappublic.s3.amazonaws.com/2016-10-25/20-32/b9a7368d-3288-44dc-a52a-2c82a4025d87.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/20-32/71306f48-dbeb-4df9-abc5-fbe9c12bc7d2.png'>Download original image</a>

**Browser**: Chrome 54 (Mac OS X Yosemite)
**Referer**: [https://dataservice.duke.edu/#/public_privacy](https://dataservice.duke.edu/#/public_privacy)
**Screen size**: 1280 x 800 **Browser size**: 1213 x 589

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Ok, I see that.
