### ISSUE TITLE
Usersnap Feedback - Uploading a file, Preparing to upload: remains; expecting file name to app[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#513]
**Sender**: None
**Comment**: Uploading a file, Preparing to upload: remains; expecting file name to appear on the line. Click Upload Files uploads file fine.
[Open #101 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/101)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/20-44/e83378aa-b17f-49a6-a21a-28add8772e15.png'>![Usersnap Feedback - Uploading a file, Preparing to upload: remains; expecting file name to app(...)](https://usersnappublic.s3.amazonaws.com/2016-10-25/20-44/f654468d-ed24-4ade-b3ef-ae40ad0cf1fe.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/20-44/e83378aa-b17f-49a6-a21a-28add8772e15.png'>Download original image</a>

**Browser**: Chrome 54 (Mac OS X Yosemite)
**Referer**: [https://dataservice.duke.edu/#/project/b300bb5e-2730-4e3f-ab2d-4d48f5557425](https://dataservice.duke.edu/#/project/b300bb5e-2730-4e3f-ab2d-4d48f5557425)
**Screen size**: 1280 x 800 **Browser size**: 1213 x 589

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
The file name is on the line? **PACE Top 10 applications.xlsx**

**Comment by jonturneratduke** [comment]
Just spoke with Nancy. I think the problem is the text "preparing to upload" remaining, it's confusing. That gives the impression that something is working, and the user should wait. She's expecting to see only the file name.  If instead it said "ready to upload: blahblah.doc" or only just the file name, that might be clearer.
