### ISSUE TITLE
Usersnap Feedback - I am testing tagging in Prod... I uploaded 10 files and then applied 3 tag[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#516]
**Sender**: james.fayson@duke.edu
**Comment**: I am testing tagging in Prod... I uploaded 10 files and then applied 3 tags to these files and received the following error
[Open #102 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/102)

<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/22-08/5d27ffeb-809c-4aba-acf9-12f44a76d195.png'>![Usersnap Feedback - I am testing tagging in Prod... I uploaded 10 files and then applied 3 tag(...)](https://usersnappublic.s3.amazonaws.com/2016-10-25/22-08/fd5c5d20-1bd5-470f-87f7-db711892adcc.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-10-25/22-08/5d27ffeb-809c-4aba-acf9-12f44a76d195.png'>Download original image</a>

**Browser**: Chrome 54 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/folder/63af0132-8b3b-475d-b5b5-30112bdac8c6](https://dataservice.duke.edu/#/folder/63af0132-8b3b-475d-b5b5-30112bdac8c6)
**Screen size**: 1280 x 720 **Browser size**: 1707 x 789

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@Donmurry @dmlond This is an API/swift issue. 500 error shows as it should in the portal. I have also seen a handful of intermittent 500 errors when testing uploads on ua_test today.
Migrating this issue to DDS
