### ISSUE TITLE
Usersnap Feedback - some major rendering funkiness  >8-O

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#542]
**Sender**: jonathan.turner@duke.edu
**Comment**: some major rendering funkiness  >8-O
[Open #104 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/104)

<a href='https://usersnappublic.s3.amazonaws.com/2016-12-15/17-54/f8d5ab19-9193-461d-bfb8-512dc8c65019.png'>![Usersnap Feedback - some major rendering funkiness  >8-O](https://usersnappublic.s3.amazonaws.com/2016-12-15/17-54/f59480ab-06c3-4d9f-bde7-887264c6ed73.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-12-15/17-54/f8d5ab19-9193-461d-bfb8-512dc8c65019.png'>Download original image</a>

**Browser**: Firefox 50 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/home](https://dataservice.duke.edu/#/home)
**Screen size**: 1680 x 1050 **Browser size**: 1486 x 829

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Need to look at hosting the icon library in the app rather than using a CDN... I think that will solve this weird transient issue.
