### ISSUE TITLE
Usersnap Feedback - I feel like this dialog has a lot of stuff sort of hanging out in white sp[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#543]
**Sender**: erich.huang@duke.edu
**Comment**: I feel like this dialog has a lot of stuff sort of hanging out in white space. Consider a text entry box. A bit more like Box's UX (though it's not super great)
[Open #105 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/105)

<a href='https://usersnappublic.s3.amazonaws.com/2016-12-15/22-43/9c808dc5-e8d7-4664-9fd3-b23a3bca137a.png'>![Usersnap Feedback - I feel like this dialog has a lot of stuff sort of hanging out in white sp(...)](https://usersnappublic.s3.amazonaws.com/2016-12-15/22-43/c87ef5ba-b1b0-4cd5-bb15-bf66b8e48ce4.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-12-15/22-43/9c808dc5-e8d7-4664-9fd3-b23a3bca137a.png'>Download original image</a>

**Browser**: Safari 10 (Macintosh)
**Referer**: [https://dev.dataservice.duke.edu/#/project/ac8c8d28-b125-43fa-acb2-4f121c0a42cd](https://dev.dataservice.duke.edu/#/project/ac8c8d28-b125-43fa-acb2-4f121c0a42cd)
**Screen size**: 2560 x 1440 **Browser size**: 1717 x 1352

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Yeah, the Material Design specs don't really use a text box like you see in the the Box UI. And it would be completely different from the rest of the text field components in the portal UI. Maybe using some dividers to provide separation or something like that would be a better way to go here.

**Comment by caseychoiniere** [comment]
I'm going to replace the upload button and text field with a dropzone box instead. That will help delineate the components in this form better, plus it will add drag and drop functionality (not including folders).
