### ISSUE TITLE
Usersnap Feedback - Probably need some indication that a Metadata Template is available/filled [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#544]
**Sender**: erich.huang@duke.edu
**Comment**: Probably need some indication that a Metadata Template is available/filled out for this file
[Open #106 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/106)

<a href='https://usersnappublic.s3.amazonaws.com/2016-12-15/22-55/d8465ebb-39d7-4f82-ac48-5bf998cfd764.png'>![Usersnap Feedback - Probably need some indication that a Metadata Template is available/filled (...)](https://usersnappublic.s3.amazonaws.com/2016-12-15/22-55/e4bcf286-1121-45ad-a229-e8268b72e7ae.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2016-12-15/22-55/d8465ebb-39d7-4f82-ac48-5bf998cfd764.png'>Download original image</a>

**Browser**: Safari 10 (Macintosh)
**Referer**: [https://dev.dataservice.duke.edu/#/file/d1ceadb3-d5dc-4881-8cf5-aac3a7776c62](https://dev.dataservice.duke.edu/#/file/d1ceadb3-d5dc-4881-8cf5-aac3a7776c62)
**Screen size**: 2560 x 1440 **Browser size**: 1717 x 1352

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Sorry, I'm confused by this feedback. The way the metadata feature works is that once the user has created a template it is available for use on any file. It is a tab inside of the tag manager screen. Once the user has created a metadata object for a file by using a metadata template, additional custom metadata will show in the file details view.

**Comment by caseychoiniere** [comment]
<img width="1257" alt="screen shot 2016-12-15 at 4 12 21 pm" src="https://cloud.githubusercontent.com/assets/10411174/21245685/4c4e8490-c2e1-11e6-90b2-a708a8f3e01f.png">
