### ISSUE TITLE
Usersnap Feedback - Anyway to do batch uploads?

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#550]
**Sender**: dma34@duke.edu
**Comment**: Anyway to do batch uploads?

[Open #107 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/107)

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-11/15-41/cfb63578-e4ee-4016-a0dc-dd7aaf5c618b.png'>![Usersnap Feedback - Anyway to do batch uploads?](https://usersnappublic.s3.amazonaws.com/2017-01-11/15-41/858d3ba8-3abf-4241-80eb-6ec1b94f0898.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-11/15-41/cfb63578-e4ee-4016-a0dc-dd7aaf5c618b.png'>Download original image</a>

**Browser**: Chrome 55 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/folder/3cdb6465-9e25-4529-972b-c661d43d2503](https://dataservice.duke.edu/#/folder/3cdb6465-9e25-4529-972b-c661d43d2503)
**Screen size**: 1536 x 864 **Browser size**: 1536 x 711

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I responded to this user
