### ISSUE TITLE
Upload error handling

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#554]
- It seems there are some holes in the upload error handling. A user had an upload fail with a 500 error and for some reason the portal didn't catch this. Need to test find and fix.

**Comment by jonturneratduke** [comment]
Interesting. Do we have any details on the failure (who/what file) and more importantly, the source (portal or python client)?  If you can pass me an file/object ID or something to start with I can followup to gather more info and chase this.

**Comment by caseychoiniere** [comment]
@jonturneratduke  Thanks Jon but I think DL is on it. I already created an issue in the DDS repo. Darin said that this had to do with problems they're experiencing with Elasticsearch index creation. You can see the conversation here https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/875 
But this highlighted for me that there is a hole/s in the error handling of the portal upload script.
