### ISSUE TITLE
Usersnap Feedback - I created a relation betw. file 20 (derived from) file 19. closed the prov[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#558]
**Sender**: jonathan.turner@duke.edu
**Comment**: I created a relation betw. file 20 (derived from) file 19. closed the provenance. opened it again and I didnt' see the relationship so I tried to add it again. got an error message (went away when I clicked usersnap). I will screenshot and email to you Casey.

[Open #111 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/111)

<a href='https://usersnappublic.s3.amazonaws.com/2017-01-19/23-49/f76352f0-99f4-4b5b-95bd-841da53bceb9.png'>![Usersnap Feedback - I created a relation betw. file 20 (derived from) file 19. closed the prov(...)](https://usersnappublic.s3.amazonaws.com/2017-01-19/23-49/03389c41-d95f-4aae-8f9b-3745d39fd2dd.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-01-19/23-49/f76352f0-99f4-4b5b-95bd-841da53bceb9.png'>Download original image</a>

**Browser**: Firefox 50 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/file/57b2a487-de94-410c-aad1-e02dd9a59ecd](https://dataservice.duke.edu/#/file/57b2a487-de94-410c-aad1-e02dd9a59ecd)
**Screen size**: 1680 x 1050 **Browser size**: 1354 x 925

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I'm 99.9999999% sure this is not a portal issue. Latent issues with the prov service still exist. Migrated this to a preexisting  DDS issue https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/876. I think it is related.
