### ISSUE TITLE
Usersnap Feedback - I am attempting to add a co-worker to this project. Her Net ID is SHEBLE. [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#575]
**Sender**: dma34@duke.edu
**Comment**: I am attempting to add a co-worker to this project. Her Net ID is SHEBLE.

I have attempted to use Net ID, Full Name and e-mail address.

Please advise.

[Open #112 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/112)

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-01/17-48/41e76a0a-5e26-4c12-b280-2165b001a861.png'>![Usersnap Feedback - I am attempting to add a co-worker to this project. Her Net ID is SHEBLE. (...)](https://usersnappublic.s3.amazonaws.com/2017-02-01/17-48/c2a3a1d5-e018-4159-a335-a22f32e4843a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-01/17-48/41e76a0a-5e26-4c12-b280-2165b001a861.png'>Download original image</a>

**Browser**: Chrome 55 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/project/84b0d207-8136-494f-82ad-bdf2a89ad84f](https://dataservice.duke.edu/#/project/84b0d207-8136-494f-82ad-bdf2a89ad84f)
**Screen size**: 1536 x 864 **Browser size**: 1536 x 711

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke Can you see if you can find out why this person isn't in the system? If there name is in in the system it will show up in the autocomplete. I'd really appreciate it.

**Comment by jonturneratduke** [comment]
email checks out. User is in directory but autocomplete doesn't work for anyone other than users who have logged in.

**Comment by caseychoiniere** [comment]
Got it. Sent this info on to the user. I can certainly see how this might be frustrating to people. Would be nice if there was some way to send out invitation links for project access/permissions via email.
