### ISSUE TITLE
Rectify apiToken and isLoggedIn issue

### ISSUE THREAD

**Issue by dburdick** [Duke-Translational-Bioinformatics/duke-data-service-portal#6]
in the App page these are being sourced from cookies, and essentially duplicated. i.e. this.state.apiToken and this.state.appConfig.apiToken. apiToken should be loaded and set into appConfig in the MainStore's constructor, and App reworked to not use the versions outside of appConfig

**Comment by caseychoiniere** [comment]
Fixed
