### ISSUE TITLE
File upload > 4GB no server upload activity

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service-portal#60]
I can initiate upload for files <= 4GB (4194306737 bytes), but if I attempt >= 4.5GB (4718598481 bytes) the progress bar is rendered, but no HTTP upload server traffic is ever initiated - progress bar just keeps rendering.  This is in Firefox.

**Comment by mgardnerpsu** [comment]
Occurs in all browsers (Chrome, Firefox, Safari) at different file size thresholds - always in the 1GB - 5GB range.  Safari reports the following error in debugger: `blob:https://dev.dataservice.duke.edu/d0d523f7-87fb-43a2-ae4d-bd378b535bf0 - An error occurred trying to load the resource.`

**Comment by caseychoiniere** [comment]
HTML5 file API FileReader is silently failing when handling a file of ~4GB. Looking into solutions to this but not finding a lot of information on handling files larger than this in the browser. Even prepackaged solutions such as resumable.js are only meant to handle files around ~4GB. Not sure if uploading through the browser with javascript will be the ultimate, robust solution that we need if we want to handle files of 10-15GB regularly. A lot of solutions I see implement a Java applet or something along those lines. I will continue to work on it for now.

**Comment by erichhuang** [comment]
You all have made major progress on this, right? Just keeping it up here to be closed out.
