### ISSUE TITLE
Usersnap Feedback - Recurring 500 errors from dataservice.duke.edu when trying to delete proje[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#600]
**Sender**: daniel.somers@duke.edu
**Comment**: Recurring 500 errors from dataservice.duke.edu when trying to delete projects. Latest occurrence is 15:31 Feb 20, 2017 attempting to delete the GCB_ruschelab2 project. 
[Open #113 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/113)

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-20/21-33/baa87ed6-92a2-48f5-862a-2591de0239a1.png'>![Usersnap Feedback - Recurring 500 errors from dataservice.duke.edu when trying to delete proje(...)](https://usersnappublic.s3.amazonaws.com/2017-02-20/21-33/11b3d2af-b80f-42e8-a2e4-d7ce0e252843.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-20/21-33/baa87ed6-92a2-48f5-862a-2591de0239a1.png'>Download original image</a>

**Browser**: Chrome 55 (Linux)
**Referer**: [https://dataservice.duke.edu/#/](https://dataservice.duke.edu/#/)
**Screen size**: 1680 x 1050 **Browser size**: 1492 x 816

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Migrated issue to DDS
