### ISSUE TITLE
Usersnap Feedback - Another 500 error attempting to delete the GCB_garmanlab project. Time 15:[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#601]
**Sender**: daniel.somers@duke.edu
**Comment**: Another 500 error attempting to delete the GCB_garmanlab project. Time 15:37 February 20, 2017.
[Open #114 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/114)

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-20/21-37/caf8baf2-4e8d-4ba4-ad5d-96298767e459.png'>![Usersnap Feedback - Another 500 error attempting to delete the GCB_garmanlab project. Time 15:(...)](https://usersnappublic.s3.amazonaws.com/2017-02-20/21-37/ec0417d3-4e5e-4d87-99bf-b1f244ab1b98.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-20/21-37/caf8baf2-4e8d-4ba4-ad5d-96298767e459.png'>Download original image</a>

**Browser**: Chrome 55 (Linux)
**Referer**: [https://dataservice.duke.edu/#/](https://dataservice.duke.edu/#/)
**Screen size**: 1680 x 1050 **Browser size**: 1492 x 816

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Migrated issue to DDS
