### ISSUE TITLE
Usersnap Feedback - I think we should have an option to tag a folder and recursively tag all c[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#604]
**Sender**: erich.huang@duke.edu
**Comment**: I think we should have an option to tag a folder and recursively tag all constituent files.
[Open #116 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/116)

<a href='https://usersnappublic.s3.amazonaws.com/2017-02-24/03-16/4d53cb40-ba3b-4387-b3eb-96cb8557dfe8.png'>![Usersnap Feedback - I think we should have an option to tag a folder and recursively tag all c(...)](https://usersnappublic.s3.amazonaws.com/2017-02-24/03-16/04798a80-27fd-4fd9-92b1-9a91f138d5d9.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-02-24/03-16/4d53cb40-ba3b-4387-b3eb-96cb8557dfe8.png'>Download original image</a>

**Browser**: Safari 10 (macOS Sierra)
**Referer**: [https://dataservice.duke.edu/#/folder/31c12a16-5051-4b75-b390-d9c93ff20fda](https://dataservice.duke.edu/#/folder/31c12a16-5051-4b75-b390-d9c93ff20fda)
**Screen size**: 1680 x 1050 **Browser size**: 1680 x 962

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Agree this would be nice.  Moving this to the DDS repo
