### ISSUE TITLE
Upload does not report error for lost network or resume

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service-portal#61]
If an upload is initiated and the network connection is dropped, the upload progress bar continues rendering, but when network connection is re-established the upload does not resume.

**Comment by mgardnerpsu** [comment]
For mvp - we just need to terminate progress bar and provide a good error message to user.

**Comment by caseychoiniere** [comment]
Added error handling for lost network. Going to change from bug to enhancement. I want to support resumable uploads.
