### ISSUE TITLE
Had to enter captcha for crypto js resources

### ISSUE THREAD

**Issue by mgardnerpsu** [Duke-Translational-Bioinformatics/duke-data-service-portal#62]
Both Erich and I encountered the following error: `Uncaught ReferenceError: CryptoJS is not defined`
We had to navigate to the crypto URIs referenced in the script tags below and key in a captcha to resolve this issue.
`<script src="https://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/md5.js"></script>`
`<script src="https://crypto-js.googlecode.com/svn/tags/3.1.2/build/components/lib-typedarrays-min.js"></script>`

**Comment by erichhuang** [comment]
I guess for some reason we're triggering some logic at Google's CDN that then elicits the CAPTCHA.

**Comment by erichhuang** [comment]
Fixed. CryptoJS components needed for the Portal have been pulled into `app/lib`
