### ISSUE TITLE
When logging out from within a Project, Portal should redirect to Login Page

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#64]
Right now, if you logout while in a Project, it strands you in an empty project page.

**Comment by caseychoiniere** [comment]
Erich, I'm not able to recreate this. Seems that it always redirects to the login page when I log out from anywhere in the app. Are you still having this issue? I'm using a logout method to clear out the apiToken and then reload the page. The main app page checks for an apiToken and if there's not one it redirects to the login page. `handleLogout () {
        this.appConfig.apiToken = null;
        cookie.remove('apiToken');
        cookie.remove('isLoggedIn');
        this.trigger({
            appConfig: this.appConfig
        });
        location.reload();
    },` and in main app page 
`if (!this.state.appConfig.apiToken && !this.state.appConfig.isLoggedIn && this.props.routerPath !== '/login') {
                this.props.appRouter.transitionTo('/login')
        }` If you have any more info on how I can recreate this I'll look into it, otherwise I'll sideline it for now.

**Comment by erichhuang** [comment]
Yeah, still having it. I'd think from you `handleLogout()` function that it should behave. I'm not sure why it's not. We can push post-MVP if other more important bugs can be quickly addressed pre STRA

**Comment by erichhuang** [comment]
See this Quicktime: https://uatest.dataservice.duke.edu/portal/#/file/0bb90e84-aa99-42c4-ab59-28dd5ca6895c

**Comment by caseychoiniere** [comment]
I can't replicate this when running my local instance for some reason. Works fine on all browsers but it's obviously not working on dev or uatest. I'm working on upload instead for now.
