### ISSUE TITLE
404 on Software Agents page for new users (users with no api_key)

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service-portal#640]
We had a new user trying to setup an agent key who receives a 404 at https://dataservice.duke.edu/#/agents. The screen loads correctly for a brief second then switches to the 404 screen. I found that by going into the apiexplorer and creating the users api_key via PUT to /api/v1/current_user/api_key the problem went away.

Steps to reproduce with a user that already has an api_key on dev.
- Go to https://apidev.dataservice.duke.edu/apiexplorer
- Click Authenticate following the prompts there
- Click 'Try it out!' at DELETE current user api key: https://apidev.dataservice.duke.edu/apiexplorer#!/current_user/deleteApiV1CurrentUserApiKey
- Go back to https://dev.dataservice.duke.edu/#/agents and see 404 error

**Comment by johnbradley** [comment]
You can also reproduce this entirely within the portal by deleting your user key after locking onto a software agent.

**Comment by caseychoiniere** [comment]
@dmann or @dmlond I have an open PR that addresses this issue. Can one of you please review and merge when you get a chance? Thanks! https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/pull/642

**Comment by johnbradley** [comment]
I tested in dev and can no longer see this issue.
Thanks @caseychoiniere
