### ISSUE TITLE
Usersnap Feedback - Hello DDS devs,  I am getting 500 response when trying to delete any of th[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#641]
**Sender**: None
**Comment**: Hello DDS devs,

I am getting 500 response when trying to delete any of the projects I currently own.

Thanks for taking a look,
Joey
[Open #118 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/118)

<a href='https://usersnappublic.s3.amazonaws.com/2017-04-18/20-00/6b8f7b69-145e-4a39-a8e3-ec1f22403968.png'>![Usersnap Feedback - Hello DDS devs,  I am getting 500 response when trying to delete any of th(...)](https://usersnappublic.s3.amazonaws.com/2017-04-18/20-00/7b8288af-ae99-400a-80d7-73c60d3d2a25.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-04-18/20-00/6b8f7b69-145e-4a39-a8e3-ec1f22403968.png'>Download original image</a>

**Browser**: Firefox 52 (Linux)
**Referer**: [https://dataservice.duke.edu/#/project/53ebd9d8-86f1-4741-a9ba-f444278753e3](https://dataservice.duke.edu/#/project/53ebd9d8-86f1-4741-a9ba-f444278753e3)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 998

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Closing here and migrating this issue over to DDS
