### ISSUE TITLE
Project Metadata should show size of total storage for all children [Project]

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#66]

**Comment by caseychoiniere** [comment]
@mgardnerpsu @erichhuang  Should there be an API endpoint for this? With the current endpoints that are available, it would be pretty contrived to get this data to display in project metadata.

**Comment by mgardnerpsu** [comment]
Yes - I think this should be the same endpoint that is used to get count of "Collaborators" as we discussed earlier this week (i.e. `/projects/{id}/metrics`} - I can add this to API git issues and assign to "me"...
