### ISSUE TITLE
Usersnap Feedback - In firefox clicking on the checkboxes beside files opens up the file inste[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#663]
**Sender**: john.bradley@duke.edu
**Comment**: In firefox clicking on the checkboxes beside files opens up the file instead of just checking it. You see the box get checked but the screen changes and you see file details. I am running Firefox 53.0.2 64-bit on OSX 10.11.6. This isn't my primary browser so it's not an issue for me just thought you would like to know.
[Open #121 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/121)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-09/22-08/0e12c03c-a2a9-4a46-82ec-d9365a107d71.png'>![Usersnap Feedback - In firefox clicking on the checkboxes beside files opens up the file inste(...)](https://usersnappublic.s3.amazonaws.com/2017-05-09/22-08/3f661de1-1f4b-43f8-be18-3d7319c61821.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-09/22-08/0e12c03c-a2a9-4a46-82ec-d9365a107d71.png'>Download original image</a>

**Browser**: Firefox 53 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/folder/06388b66-97f5-460a-8b0f-c1f6333f14f5](https://dataservice.duke.edu/#/folder/06388b66-97f5-460a-8b0f-c1f6333f14f5)
**Screen size**: 1440 x 900 **Browser size**: 1359 x 720

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Thanks @jonturneratduke . This was logged a while ago. It's fixed on ua_test and dev with the redesign it just hasn't made it to prod yet.
