### ISSUE TITLE
Safari multi download

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#664]
Batch downloads don't work in Safari unless the user explicitly turns off their pop-up blocker. Unfortunately theirs no elegant solution to this problem right now. In FF and Chrome I was able to work around the pop up blocker by opening the swift download URL in a new tab if the pop-ups were blocked. 

Safari prevents this workaround and throws `Failed to load resource: Frame load interrupted` error after the first download if pop-ups aren't enabled.

For now I am sniffing for Safari and displaying  a message to the user that they need to enable pop-ups in order to download files.

**Comment by jonturneratduke** [comment]
Given all the limitations, I think that's a great solution. It gets things working, where possible, and tells the user what to do otherwise. Nice!
