### ISSUE TITLE
Usersnap Feedback - Not able to add a file to the graph. The Submit button doesn't seem to do [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#674]
**Sender**: jonathan.turner@duke.edu
**Comment**: Not able to add a file to the graph. The Submit button doesn't seem to do anything. I've tried adding files in the same project,and from other projects without success. Maybe a firefox thing?
[Open #122 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/122)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-15/21-43/8a1b1f53-a7ed-4e0f-9fcf-1622ff55d2df.png'>![Usersnap Feedback - Not able to add a file to the graph. The Submit button doesn't seem to do (...)](https://usersnappublic.s3.amazonaws.com/2017-05-15/21-43/a7ac1534-cdba-41b2-ac73-8a9fc9c74593.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-15/21-43/8a1b1f53-a7ed-4e0f-9fcf-1622ff55d2df.png'>Download original image</a>

**Browser**: Firefox 53 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/file/f37802ae-0f19-4e16-be67-8654c2adfd16](https://dataservice.duke.edu/#/file/f37802ae-0f19-4e16-be67-8654c2adfd16)
**Screen size**: 1680 x 1050 **Browser size**: 1676 x 925

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke That's odd. I just logged into the portal in both FF and Chrome and had no problem adding files to the graph. Any more info that might be relevant? Did you try adding files into a different prov graph? Also, ca you check the console for errors and let me know if you're getting any. Thanks!

**Comment by caseychoiniere** [comment]
This seems to be isolated to this one project for some reason. Sounds like a bunch of different provenance was created programmatically for these files. Something about the provenance that was created seems to be keeping the graph canvas from rendering.
