### ISSUE TITLE
Usersnap Feedback - Deleted 20 files in prod and receive the 500 error

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#677]
**Sender**: james.fayson@duke.edu
**Comment**: Deleted 20 files in prod and receive the 500 error
[Open #123 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/123)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-16/03-20/100d559f-fe31-4e89-9b1a-fd8f1c0df661.png'>![Usersnap Feedback - Deleted 20 files in prod and receive the 500 error](https://usersnappublic.s3.amazonaws.com/2017-05-16/03-20/11afb329-815d-4fa1-a554-a18482474de8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-16/03-20/100d559f-fe31-4e89-9b1a-fd8f1c0df661.png'>Download original image</a>

**Browser**: Chrome 58 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/project/a4fa5e15-695b-439a-becb-ee7e3de1a1f7](https://dataservice.duke.edu/#/project/a4fa5e15-695b-439a-becb-ee7e3de1a1f7)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 592

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Moving this over to DDS
