### ISSUE TITLE
Send link of asset to user interface [File Download]

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#69]
Probably something similar to Dropbox/Google Drive

**Comment by erichhuang** [comment]
This would be like right-clicking on a Dropbox item and having a link (or even better shortened link) saved to the Clipboard.

**Comment by jonturneratduke** [comment]
+1  This will add greatly to usability.

Of course to see the asset, one must be a member of the project. Should we add "public sharing links" to the future feature pile?

**Comment by caseychoiniere** [comment]
Needs a service for this. Right now DDS returns a temporary download URL that has a short expiration date. In the form of `/v1/AUTH_frds/25c83864-7c9e-44ae-9ea9-49dc05282575/d67ad052-a7fa-4823-84c5-e12ab58c0e41?temp_url_sig=b956396a681f6a0b18156fd771e600722d3b7ae0&temp_url_expires=1472230142&filename=temp_10B_file%20copy%20(2)` as an example. So this should probably be a DDS issue/feature request as well.

**Comment by dmlond** [comment]
The easiest thing we could do is have an endpoint that generates a swift temporary url with a longer expiration. That would generate a url that is consumable by any http client. Something else would likely involve us figuring out how to better use swift to provide [temporary] public access to a specific file. This might require a separate 'public' container for each project that stores objects that any person anywhere can download without a temporary url or access key.
