### ISSUE TITLE
Adding Users to Project

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#70]
I can't add Jonathan Turner to a project. My suspicion is that there are multiple people with that name at Duke and that's the SNAFU.

In any case, we should have autocomplete/typeahead and picker interface in next versions.

**Comment by erichhuang** [comment]
Will map this over to the `duke-data-service` repo

**Comment by caseychoiniere** [comment]
I think this is covered from the UI perspective. Closing this issue.
