### ISSUE TITLE
Usersnap Feedback - would it be possible to show different icons for different data types inst[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#722]
**Sender**: jonathan.turner@duke.edu
**Comment**: would it be possible to show different icons for different data types instead of blue bubble? - michael gunn
[Open #129 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/129)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-25/21-00/bd3603bb-5636-41a2-9a94-265684bfae6e.png'>![Usersnap Feedback - would it be possible to show different icons for different data types inst(...)](https://usersnappublic.s3.amazonaws.com/2017-08-25/21-00/cfcb4ec8-14ca-4088-81f1-67d6c1b2845e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-25/21-00/bd3603bb-5636-41a2-9a94-265684bfae6e.png'>Download original image</a>

**Browser**: Firefox 55 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/file/0a2ceaeb-2442-4adc-9bc1-d8e0daedfab0](https://dataservice.duke.edu/#/file/0a2ceaeb-2442-4adc-9bc1-d8e0daedfab0)
**Screen size**: 1920 x 1080 **Browser size**: 1669 x 779

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke @Donmurry  This isn't really supported by the graphing lib we're using. In addition, it would require the client somehow knowing **all** of the possible data types that might be stored in DDS. 

Can someone reach out to this user and let them know. I don't see their email address. 

Thanks!

**Comment by jonturneratduke** [comment]
Thanks, Casey. It was a suggestion made while demoing to Dr. Michael Dee Gunn. If we were able to represent even a few known types (.doc, .txt, .csv, .bin) and leave the rest as blue bubbles that would improve usability.

**Comment by caseychoiniere** [comment]
It's an interesting suggestion. We could work this in and add icons but I have a few questions/concerns.

The general idea behind icons for improving usability is that the icon immediately represents an action or object in a way that is recognizable by a user. So in general if you see :heavy_exclamation_mark: you know that it is trying to represent a warning or if you see :telephone_receiver: you know this represents a telephone number or contact. 

What does a `.csv` icon look like? And how does a `.txt` icon differ from a `.bin` or `.xls`?

I guess what I'm getting at here is maybe there's a better way to represent the node datatype and improve visual usability than by adding random icons. Perhaps printing the file extension inside the node in bold? Or adding the file extension and a custom node color? 

In addition, if we use some random icons on the request of a few users it might end up just being more confusing for users who don't know about this or don't need (want) this UX. 

Let me ruminate a bit about this. And if anyone else has any good ideas that would be beneficial.

**Comment by dmlond** [comment]
could this be more like my android phone, where I can associate a specific ringtone to each contact. If users dont need the UX, they get the blue blobs by default. But a user could set up their preferences to map a content-type to a different icon (probably chosen from a carefully curated set of icons). This would only show up for them.

**Comment by caseychoiniere** [comment]
Maybe. If the API supported that it could be done. Seems like a lot of development effort. I'm just wondering if there's a better middle way. That being said, I get paid by the hour :smirk:

**Comment by jonturneratduke** [comment]
>>What does a .csv icon look like? And how does a .txt icon differ from a .bin or .xls?
as always, you and DL have good points. A curated small list would probably be the best compromise on this path, but we should stop and think first, what is the deeper problem being solved.

But, I suspect what he's really after is reducing the difficulty of selecting files. If all the files in the project are listed, that's too many, and this was proposed as a way of visually reducing the list to a manageable set. I think this is deeper than just icons - it probably involves filtering the list by file type, folder, date, etc. 

Dr Gunn discussed a workflow in his group and how he imagines using DS to store his lab's data. He works from the bottom-up, storing low-level data files, then adding analysis files that reference the low-level data files, then another level up that might combine several analysis files, etc. all the way up to the top where a PDF might sit. What he's really after is a way to add a file and at that instant describe how it's related to the other files. When he adds a lowest-level data file, that file stands alone. But when he adds an analysis file, he wants to be able to say that it references a few files "below" it.
Much like when we check in code we describe the changes we made, he wants to describe the relationship metadata at the time he "checks in" his files. And as there might be dozens of files he's looking to make that choice easier and more intuitive.

We need a break-out discussion to get to the bottom of this, I think.

**Comment by caseychoiniere** [comment]
Thank you for the detailed description. This makes more sense now. What I hear you saying is that the real problem lies with the file selection capability and the immediate ability to define activities and relations to other files. 

In addition, it sounds like other parts of the current UI/UX isn't the best match for the workflow he is describing.

Keep me posted after you discuss this.
