### ISSUE TITLE
Usersnap Feedback - would like to be able to view this relationship in a hierarchical format l[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#723]
**Sender**: jonathan.turner@duke.edu
**Comment**: would like to be able to view this relationship in a hierarchical format like Microsoft publisher -  michael gunn via jonathan.turner@duke.edu
[Open #130 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/130)

<a href='https://usersnappublic.s3.amazonaws.com/2017-08-25/21-00/bc909cf0-8054-43ff-a070-55a2a8b32519.png'>![Usersnap Feedback - would like to be able to view this relationship in a hierarchical format l(...)](https://usersnappublic.s3.amazonaws.com/2017-08-25/21-00/a65f0d51-e291-4d67-8a9d-4b91d1b6b939.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-08-25/21-00/bc909cf0-8054-43ff-a070-55a2a8b32519.png'>Download original image</a>

**Browser**: Firefox 55 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/file/0a2ceaeb-2442-4adc-9bc1-d8e0daedfab0](https://dataservice.duke.edu/#/file/0a2ceaeb-2442-4adc-9bc1-d8e0daedfab0)
**Screen size**: 1920 x 1080 **Browser size**: 1669 x 779

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke @Donmurry I'm not sure I follow. This is a hierarchical layout. It's the standard suggestion for graphing provenance. It is basically an upside down directed tree graph (the proper name is escaping me at the moment). 

Example from docs of graph library here. You can click on the "Down-Up" button to see a hierarchical layout that is the same as the one we're using.

http://visjs.org/examples/network/layout/hierarchicalLayout.html
