### ISSUE TITLE
Usersnap Feedback - Just clicking Credentials on this screen recreates my user_key. This messe[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#744]
**Sender**: john.bradley@duke.edu
**Comment**: Just clicking Credentials on this screen recreates my user_key. This messes up ddsclient config files.
[Open #132 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/132)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-13/21-56/9fe43fe7-2f7a-4298-9979-8b3230fcdfae.png'>![Usersnap Feedback - Just clicking Credentials on this screen recreates my user_key. This messe(...)](https://usersnappublic.s3.amazonaws.com/2017-10-13/21-56/112a90fc-ea61-419a-8b47-3203a540977c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-13/21-56/9fe43fe7-2f7a-4298-9979-8b3230fcdfae.png'>Download original image</a>

**Browser**: Chrome 61 (macOS Sierra)
**Referer**: [https://dev.dataservice.duke.edu/#/agents](https://dev.dataservice.duke.edu/#/agents)
**Screen size**: 1920 x 1080 **Browser size**: 1357 x 788

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke Yeah, it really shouldn't. It first checks whether you even have a user key before creating these credentials but perhaps there's a race condition here. If you have a user key it shouldn't be creating a new one. Honestly the API should probably just have an endpoint that returns current credentials. As it is it's kind of a hack how we're doing this in the portal. I don't have the code in front of me at the moment, but I'm fairly certain that this requires three separate API calls just to build these credentials.

**Comment by caseychoiniere** [comment]
I will put this on my list of things to work on next week

**Comment by caseychoiniere** [comment]
@jonturneratduke Just created a PR to fix this https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/pull/745

Should go live early next week. Sorry about the hassle.
