### ISSUE TITLE
Usersnap Feedback - What is this empty Project Admin role?

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#748]
**Sender**: holly.dressman@duke.edu
**Comment**: What is this empty Project Admin role?
[Open #133 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/133)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-20/16-00/eca483f9-3e32-4104-876a-ef378e0b517b.png'>![Usersnap Feedback - What is this empty Project Admin role?](https://usersnappublic.s3.amazonaws.com/2017-10-20/16-00/51ca64cf-f2b7-44db-9cbf-0e649574640c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-20/16-00/eca483f9-3e32-4104-876a-ef378e0b517b.png'>Download original image</a>

**Browser**: Chrome 61 (Windows 7)
**Referer**: [https://dataservice.duke.edu/#/project/d5192cca-3cf1-436f-8252-47b0786af23f](https://dataservice.duke.edu/#/project/d5192cca-3cf1-436f-8252-47b0786af23f)
**Screen size**: 1536 x 864 **Browser size**: 1536 x 755

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke I migrated this issue as well as #749 over to the DDS API repo. 

Issue is here https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/1092
