### ISSUE TITLE
Usersnap Feedback - owner/creator for project and subfolder is "null" in the Wei_4405 Project, [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#749]
**Sender**: jonathan.turner@duke.edu
**Comment**: owner/creator for project and subfolder is "null" in the Wei_4405 Project, created by Holly Dressman.
[Open #134 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/134)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-20/16-09/f57514ea-f7d5-4af5-a7aa-ee932a92b0be.png'>![Usersnap Feedback - owner/creator for project and subfolder is "null" in the Wei_4405 Project, (...)](https://usersnappublic.s3.amazonaws.com/2017-10-20/16-09/0a454d49-5d1b-40a0-b255-30c772b7ad7a.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-20/16-09/f57514ea-f7d5-4af5-a7aa-ee932a92b0be.png'>Download original image</a>

**Browser**: Firefox 56 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/project/d5192cca-3cf1-436f-8252-47b0786af23f](https://dataservice.duke.edu/#/project/d5192cca-3cf1-436f-8252-47b0786af23f)
**Screen size**: 1280 x 800 **Browser size**: 1190 x 645

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@jonturneratduke I migrated this issue as well as #748 over to the DDS API repo. 

Issue is here https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/1092
