### ISSUE TITLE
Usersnap Feedback - Search doesn't find Project names.

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#754]
**Sender**: erich.huang@duke.edu
**Comment**: Search doesn't find Project names.
[Open #135 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/135)

<a href='https://usersnappublic.s3.amazonaws.com/2017-10-26/20-58/4b701177-69b4-4a74-bf7e-c26cc019a02b.png'>![Usersnap Feedback - Search doesn't find Project names.](https://usersnappublic.s3.amazonaws.com/2017-10-26/20-58/2c662ed9-d669-423b-95c9-a4b1e2452d88.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-10-26/20-58/4b701177-69b4-4a74-bf7e-c26cc019a02b.png'>Download original image</a>

**Browser**: Chrome 61 (Macintosh)
**Referer**: [https://dev.dataservice.duke.edu/#/](https://dev.dataservice.duke.edu/#/)
**Screen size**: 1680 x 1050 **Browser size**: 1228 x 949

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
@erichhuang Yes, they haven't built project names into search yet. I think an issue was already opened for this but will double check and forward this to the team.
