### ISSUE TITLE
Usersnap Feedback - Details for viewing project with large provenance.  Error is from a  POST [...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#761]
**Sender**: john.bradley@duke.edu
**Comment**: Details for viewing project with large provenance.

Error is from a 
POST https://api.dataservice.duke.edu/api/v1/search/provenance/origin 500 (Internal Server Error)

Request Payload: {"file_versions":[{"id":"8a2dd170-d9f5-47bc-bff8-4afe61375bd3"}]}

[Open #136 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/136)

<a href='https://usersnappublic.s3.amazonaws.com/2017-11-02/16-03/8f32bb67-67a7-4329-a109-5474fa6bf1e3.png'>![Usersnap Feedback - Details for viewing project with large provenance.  Error is from a  POST (...)](https://usersnappublic.s3.amazonaws.com/2017-11-02/16-03/ada4c7ac-f87e-49ff-a58b-507c31f6b3cb.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-11-02/16-03/8f32bb67-67a7-4329-a109-5474fa6bf1e3.png'>Download original image</a>

**Browser**: Chrome 61 (macOS Sierra)
**Referer**: [https://dataservice.duke.edu/#/file/5c692216-5764-4303-a37d-27920265fbaa](https://dataservice.duke.edu/#/file/5c692216-5764-4303-a37d-27920265fbaa)
**Screen size**: 1920 x 1080 **Browser size**: 1587 x 930

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
forwarded issue to DDS repo
