### ISSUE TITLE
Usersnap Feedback - 'Select All'?

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#762]
**Sender**: erich.huang@duke.edu
**Comment**: Capitalize? Feel like these headers should look more different. Maybe bold too.
[Open #137 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/137)
**Notes**:
 - 'Select All'?

<a href='https://usersnappublic.s3.amazonaws.com/2017-11-02/16-43/5ef9ad21-bd5c-48cd-9fbd-1563d8fdcec2.png'>![Usersnap Feedback - 'Select All'?](https://usersnappublic.s3.amazonaws.com/2017-11-02/16-43/a5ccf707-71e8-4b3a-ba1e-5086e75ae1f2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-11-02/16-43/5ef9ad21-bd5c-48cd-9fbd-1563d8fdcec2.png'>Download original image</a>

**Browser**: Safari 11 (Macintosh)
**Referer**: [https://dataservice.duke.edu/#/project/2193a6b3-9a7a-40d9-99f5-cb5ace55f6bb](https://dataservice.duke.edu/#/project/2193a6b3-9a7a-40d9-99f5-cb5ace55f6bb)
**Screen size**: 1680 x 1050 **Browser size**: 1337 x 943

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
PR created https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/pull/763

![screen shot 2017-11-03 at 2 24 05 pm](https://user-images.githubusercontent.com/10411174/32396529-d1d26ff4-c0a2-11e7-85a2-12c81d0759df.png)
