### ISSUE TITLE
Usersnap Feedback - I selected all items, then clicked Tag. This brought up the "Upload" modal[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#769]
**Sender**: jonathan.turner@duke.edu
**Comment**: I selected all items, then clicked Tag. This brought up the "Upload" modal. I dismissed it, and the correct tag modal was underneath. 
[Open #138 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/138)

<a href='https://usersnappublic.s3.amazonaws.com/2017-12-01/21-48/6c3d6bd0-7859-40f6-840c-0cf815f47ef7.png'>![Usersnap Feedback - I selected all items, then clicked Tag. This brought up the "Upload" modal(...)](https://usersnappublic.s3.amazonaws.com/2017-12-01/21-48/93a6c414-6f9f-439e-8b6a-92bac4657796.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-12-01/21-48/6c3d6bd0-7859-40f6-840c-0cf815f47ef7.png'>Download original image</a>

**Browser**: Firefox 57 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/folder/747be173-d376-428c-97f1-ae38ff3653be](https://dataservice.duke.edu/#/folder/747be173-d376-428c-97f1-ae38ff3653be)
**Screen size**: 1280 x 800 **Browser size**: 1276 x 685

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Odd. I can't reproduce this. Sounds like a transient issue. I'll leave it open for now and do some more digging.
