### ISSUE TITLE
Firefox- Select all items in project, click tag button -> tag form and upload form show

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#770]
**Sender**: jonathan.turner@duke.edu
**Comment**: select all items in project, click tag button -> tag form and upload form both appear.
[Open #139 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/139)

<a href='https://usersnappublic.s3.amazonaws.com/2017-12-01/22-07/cdf5edc8-5cd5-4515-9832-89f57cea9d0a.png'>![Usersnap Feedback - select all items in project, click tag button -> tag form and upload form (...)](https://usersnappublic.s3.amazonaws.com/2017-12-01/22-07/22669ba7-9559-43c2-9586-2b782abaf4b2.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-12-01/22-07/cdf5edc8-5cd5-4515-9832-89f57cea9d0a.png'>Download original image</a>

**Browser**: Firefox 57 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/folder/747be173-d376-428c-97f1-ae38ff3653be](https://dataservice.duke.edu/#/folder/747be173-d376-428c-97f1-ae38ff3653be)
**Screen size**: 1280 x 800 **Browser size**: 1276 x 685

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
I see now. Ok, thanks. I'll dig into what's going on here. Apparently it's suddenly a mess on Firefox...

**Comment by caseychoiniere** [comment]
UploadManager, TagManager and Provenance drawers all open on screen when one of the drawers opens. 

Only occurs in newer Firefox versions

**Comment by caseychoiniere** [comment]
Created a pull request as a temporary workaround for this. It's a pretty pesky little bug and took me several hours just to identify what was causing it. I will leave this open though and put some more effort into finding a better solution than the one I've provided here.

See the pull request below
https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/pull/771
