### ISSUE TITLE
Usersnap Feedback - the last token, api_url should be "url", and we should include the path, l[...]

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#792]
**Sender**: jonathan.turner@duke.edu
**Comment**: the last token, api_url should be "url", and we should include the path, like : 
`"url": "https://api.dataservice.duke.edu/api/v1"` 
[Open #140 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/140)

<a href='https://usersnappublic.s3.amazonaws.com/2018-01-26/17-25/2d974dee-320e-4507-9e02-9a131c5fddff.png'>![Usersnap Feedback - the last token, api_url should be "url", and we should include the path, l(...)](https://usersnappublic.s3.amazonaws.com/2018-01-26/17-25/f542a861-8584-4259-916b-4027ee4ab76d.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-01-26/17-25/2d974dee-320e-4507-9e02-9a131c5fddff.png'>Download original image</a>

**Browser**: Firefox 57 (OS X El Capitan)
**Referer**: [https://dataservice.duke.edu/#/agents](https://dataservice.duke.edu/#/agents)
**Screen size**: 1280 x 800 **Browser size**: 1276 x 685

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
This fix is going to dev now. Not sure how quickly it will make it into production but probably as early as next Wednesday (1/31/2018) during the weekly maintenance window. 

https://github.com/Duke-Translational-Bioinformatics/duke-data-service-portal/pull/793
