### ISSUE TITLE
(Dashboard) - Missing add folder button

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#821]
Button missing from screen.
![screen shot 2018-03-06 at 12 26 21 pm 1](https://user-images.githubusercontent.com/10411174/37119612-cb9d4a52-220c-11e8-8e7a-f06819ecb23f.png)

**Comment by ChetCorey** [comment]
I'm not sure why that happened, but I'm not seeing that issue, but I think I fixed it by refactoring the way i'm loading components
