### ISSUE TITLE
(Software Agents) - Fix load more button in software agents listItems

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#828]
Button requests incorrect method if on software agents page

**Comment by caseychoiniere** [comment]
Fixed immediate bug but needs pagination for software agents properly refactored.

**Comment by caseychoiniere** [comment]
There is actually no pagination on the software agents API. So this has to wait until the API supports it. 

https://github.com/Duke-Translational-Bioinformatics/duke-data-service/issues/1166

**Comment by dmlond** [comment]
archive this project
