### ISSUE TITLE
Usersnap Feedback - trying to log in, but I just get the spinning circle

### ISSUE THREAD

**Issue by jonturneratduke** [Duke-Translational-Bioinformatics/duke-data-service-portal#838]
[Open #141 in Usersnap Dashboard](https://usersnap.com/a/#/development-3/p/data-service-at-e1f3b170/141)
**Notes**:
 - (1) trying to log in, but I just get the spinning circle

<a href='https://usersnappublic.s3.amazonaws.com/2018-03-17/02-08/b390adcc-1361-489c-abb6-74e36cc4fa58.png'>![Usersnap Feedback - trying to log in, but I just get the spinning circle](https://usersnappublic.s3.amazonaws.com/2018-03-17/02-08/f66d96ca-84e0-4deb-b1a4-e87dddb82b41.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-03-17/02-08/b390adcc-1361-489c-abb6-74e36cc4fa58.png'>Download original image</a>

**Browser**: Chrome 63 (Windows 7)
**Referer**: [https://dataservice.duke.edu/portal/#/login](https://dataservice.duke.edu/portal/#/login)
**Screen size**: 1280 x 720 **Browser size**: 1280 x 591

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by caseychoiniere** [comment]
Not sure what was happening for you here. Sounds like it got stuck in a loading state for some reason. I can't recreate the issue at the moment. Did you try to refresh the page?
