### ISSUE TITLE
Change verbiage in project deletion confirmation screen

### ISSUE THREAD

**Issue by caseychoiniere** [Duke-Translational-Bioinformatics/duke-data-service-portal#844]
Since we are implementing a trashbin feature it should be clear that deleted projects and their contents  will not be restorable. 

**Docs:** _The deletion of an entire project is a permanent (destructive) operation. The project and all of its contents are immediately considered "purged" and are not moved to the trash bin, therefore projects cannot be restored_

**Comment by dmlond** [comment]
archive this project
