### ISSUE TITLE
HIPAA Modal get's partially overlapped by header

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#87]
<img width="1070" alt="screen shot 2016-01-22 at 9 05 29 am" src="https://cloud.githubusercontent.com/assets/386675/12512610/5733d600-c0e7-11e5-9a61-a2dc1966dac2.png">

**Comment by caseychoiniere** [comment]
Will show changes on next build today.
