### ISSUE TITLE
When deleting a Duke DS entity, also have user type in name of entity

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#90]
e.g. when someone delete's a Project, I like the modal. What would be nice as an additional failsafe, just as Github does, is have the User type in the name of the Project before the `Delete` button becomes active. See attached image for the Github modal.

![screen shot 2016-01-22 at 13 20 32](https://cloud.githubusercontent.com/assets/386675/12519142/f8d8063e-c10a-11e5-8f11-7d44ebe5027f.png)

**Comment by caseychoiniere** [comment]
Good idea. Done. Will show on next build.
