### ISSUE TITLE
Unable to upload empty files in web portal

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service-portal#900]
I am unable to upload empty files via https://dataservice.duke.edu.
When I upload I see a message about retrying and then I see this message:
<img width="756" alt="Screen Shot 2019-05-02 at 11 38 52 AM" src="https://user-images.githubusercontent.com/1024463/57087834-ed313a80-6cce-11e9-96c9-6519653582bc.png">

I think this might be related to the s3 backend. We had a similar issue in DukeDSClient https://github.com/Duke-GCB/DukeDSClient/issues/231.

**Comment by dmlond** [comment]
This issue arose after we implemented S3 support and switched the api default storage to S3. The S3 storage systems do not support 0 byte multipart uploads. They do support 0 byte objects.

This would require the portal code to be changed:
- If there is not a compelling reason to support 0 byte files in a research data repository, the portal should warn users that 0 byte files are not supported before starting the upload process
- If there is a compelling reason to support 0 byte files in a research data repository, the portal should support non-chunked uploads, which are supported by the api

**Comment by dmlond** [comment]
archive this project
