### ISSUE TITLE
Hash for large files uploaded through portal is incorrect

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service-portal#901]
The latest version of DukeDSClient checks file hashes for files it downloads.
Any larger files uploaded through the web portal records an incorrect MD5 hash.
When these files are downloaded using DukeDSClient it errors after downloading them.
We have had users report this issue after receiving a project containing such files.

URLs to example project/file that has this problem:
https://dataservice.duke.edu/#/project/35866966-1911-467d-a940-a3d8870fab99
https://dataservice.duke.edu/#/file/5dc95ad7-c718-4460-9706-66af99efc39c

You can recreate this by uploading a file >= 10MB through the web portal.

This may be the same as what is described in issue #227 

Thanks.

**Comment by dmann** [comment]
Just released `v1.9.2` to `ua_test`, which addresses this issue. Unless something unforeseen occurs, we'll plan on releasing this to `production` during the Wednesday maintenance window.

**Comment by dmlond** [comment]
archiving this project
