### ISSUE TITLE
Allow adding users to a project when multiple users share the same name

### ISSUE THREAD

**Issue by johnbradley** [Duke-Translational-Bioinformatics/duke-data-service-portal#905]
If two users have the same name it is impossible to select the correct one via the `Manage Project Team Members` panel.
No matter which you select it seems to always fails with a 404.
Here is an example with "Steven Shin"
<img width="848" alt="Screen Shot 2020-07-09 at 1 07 10 PM" src="https://user-images.githubusercontent.com/1024463/87069435-2cb5b980-c1e5-11ea-85a6-f1f80bb07194.png">

Please update this panel to show a little more detail about the users and to assign permissions to the chosen user instead of showing a 404 error.

Thanks.

**Comment by jonturneratduke** [comment]
Under investigation now, for implementation this sprint. Goal is to have it ready for UAT Jul20.

**Comment by dmlond** [comment]
archiving this repository
