### ISSUE TITLE
Header is hiding 'Terms of Use'

### ISSUE THREAD

**Issue by Donmurry** [Duke-Translational-Bioinformatics/duke-data-service-portal#92]
Depending on the screen size the 'terms of use' is obscured.
![header_popup](https://cloud.githubusercontent.com/assets/8406722/12520887/19f0d206-c115-11e5-9296-25d641588fc3.jpg)

**Comment by caseychoiniere** [comment]
This is a duplicate issue. Made changes already and will show on next build in a little while. Have a few more small changes to make before building. #87
