### ISSUE TITLE
"Update" Button [File]

### ISSUE THREAD

**Issue by erichhuang** [Duke-Translational-Bioinformatics/duke-data-service-portal#99]
![screenshot 2016-01-26 14 10 52](https://cloud.githubusercontent.com/assets/386675/12591640/c3745d4c-c436-11e5-8bdd-baeba0e47d0b.png)

Now that we're at Alpha, it'd be nice to have an "Update" button (perhaps next to the pink "Download" button, so if one had added to a file/document, the new version could slot into it's place. 

One dependency is that the File API have some notion of `Version`, so I think we need to add that in now. I'll add a link to this Issue over in `duke-data-service` as well.

**Comment by caseychoiniere** [comment]
Perhaps we should implement a drop down menu here with options to download/update/delete the file? That way the UI won't look cluttered as we add options. I was thinking that it makes sense to add the option to delete the file (or folder) directly from the list without first clicking into the file or folder.

**Comment by caseychoiniere** [comment]
Something like 
![screen shot 2016-01-26 at 11 26 57 am](https://cloud.githubusercontent.com/assets/10411174/12592088/c8ec877a-c41f-11e5-8ce9-fafc93391fa2.png)

**Comment by caseychoiniere** [comment]
Like this 
![screen shot 2016-01-26 at 11 43 02 am](https://cloud.githubusercontent.com/assets/10411174/12592626/14ed3988-c422-11e5-927e-73d062a30ad8.png)

**Comment by erichhuang** [comment]
I'm OK with that, so we don't start looking lie a Microsoft Office product

**Comment by erichhuang** [comment]
So as with Synapse, the version of the file would be prominently displayed
![screenshot 2016-01-26 15 58 48](https://cloud.githubusercontent.com/assets/386675/12594831/059a7062-c446-11e5-90e4-90bb0c8a4a13.png) Perhaps something like this (though provide padding behind the text and the bottom rule)

@erichhuang the only issue with this is that the most current file object (project child or folder child) doesn't have a version number.

**Comment by erichhuang** [comment]
I think the major dependencies on this are:
1) Add "Version" to the File API
2) The asynchronous checksum worker feature being completed.

The way I'm thinking about this is that we are saving multiple versions of a file. If the worker identifies that a new version has a different checksum than the previous version, then the version number is incremented +1. Unfortunately, for now, this will have to be asynchronous and we will expect eventual consistency rather than in real time.
